= egeszen addig amig ez nem

:slug: egeszen_addig_amig_ez_nem
:category: film
:tags: hu
:date: 2006-11-30T17:06:26Z
++++
egeszen addig amig ez nem karosit mast v magamat, azert szeretem felrugni a szabalyokat neha, tudjatok milyen jo erzes az :) tegnap ez elegge osszejott:<br>1) ebbol a szofttech targybol amibol holnap irunk asszem igy kb az elso oran figyeltem, pedig majdnem mindig benn ultunk csak vagy csinaltam vmi ertelmeset v aludtam (jo vegulis azis ertelmes :) )<br>2) hamar az eloadason nem sikerul figyeleni erdemes felkeszulni zhra. nem a zh elotti 2 napban<br>3) hamar utolso pill-ban kene felkeszulni akkor nemkene mast csinalni<br>4) hamar mast csinalsz akkor az ne a masnapi eloadasok rovasara menjen<br>pedig tegnap olyan 2korul mar elfogyott a turelmem a tanulashoz, es mivel 8ra kellett volna bemenni, ellenalhatatlan vagyat ereztem h vmi <a href="http://www.imdb.com/title/tt0120382/" target="_self">jo filmet</a>, ezzel is biztositva, h 10 elott biztosan ne erjek be<br>a hatas garantalt :)
++++
