= errol irni kell :) tegnap

:slug: errol_irni_kell_tegnap
:category: regi
:tags: hu
:date: 2006-08-26T13:12:05Z
++++
errol irni kell :) tegnap elvileg 7tol volt Frugalware-sorozes. kb 3/4 7kor nasan ramprivizett Dia, de igazabol nem beszeltunk semmit, leven en mar rohantam el. igy kb annyit tudtam rola, h miskolci, kicsit fiatalabb nalam, es nincs pasija. kb utolso pillanatban felvetette, h milyen szivesen jonne pestre. mondom hat akkor gyere. omeg tenyleg kepes volt eljonni :) szal telszamcsere, aztan mentem ki 22:07re a keletibe ele. hogy milyen csaj lesz, hogynezki, stb stb semmit nem tudtam. dehat nyar van, ha vmi elviselhetetlen szoke picsa akkor csak azzal lesz szopas, h hogy kerul haza, de akkor ezzel nem akartam foglalkozni. kb 1 ora kesessel megerkeztem a sorozesre, le is ment jol csak a vonat miatt eleg gyorsan leleptem. utana meg kis kavaras mert a keletiben voltak bkv-ellenorok de vegul nem vagtak meg. utana meg jott a pozitiv csalodas, Dia abszolut normalis, ertelmes, csinos kiscsaj. innentol annyira nincs mit reszletezni: eloszor beultunk 1 sorre a moriczon, aztan kimentunk a feneketlen tohoz, csak kisse hideg volt igy (ez ilyen 2 korul lehetett asszem) lementunk a bmehez, vegul&nbsp; (6 korul?) elgyalogoltunk a batthyanyra, mert onnan vmi rokonukhoz ment tovabb hevvel (tessek, ezert nem kell problemazni, h milesz a vegen, neha maguktol megoldodnak a dolgok). hat kb ennyi, semmi extra, nem jottunk ossze v ilyesmi de egyreszt nagy poen volt, masreszt mostmar eztis kiprobaltam :)
++++
