= Füzet, winword,

:slug: fuzet_winword
:category: regi
:tags: hu
:date: 2006-11-15T02:39:49Z
++++
<meta http-equiv="CONTENT-TYPE" content="text/html; charset=utf-8"><title>Füzet, winword, javított, kiegészített</title><meta name="GENERATOR" content="OpenOffice.org 2.0  (Linux)"><meta name="AUTHOR" content="Somlói Zsófia"><meta name="CREATED" content="20010419;16180000"><meta name="CHANGEDBY" content="Szabó"><meta name="CHANGED" content="20010419;16180000"><meta name="CLASSIFICATION" content="a-j"> 	 	 	 	 	 	 	 	<style type="text/css"> 	<!-- 		@page { size: 21cm 29.7cm; margin: 2cm } 		P { margin-bottom: 0.21cm } 	--> 	</style>  <p style="margin-left: 1.52cm; margin-top: 0.85cm; margin-bottom: 0cm; line-height: 0.42cm;"><font size="3"><font face="Courier New, monospace"><b>C&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;           G&nbsp;  F&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;           C<br></b>Ott van <u>é</u>letem Isten tenyerén,<br><b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;              B&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       F</b><br>és azért nem félek én.<br><b>&nbsp;&nbsp;&nbsp;    C &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;           G&nbsp;  F &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;             C</b><br>Ha bármi f<u>á</u>j nekem, mosolyog szemem.<br><b>&nbsp; C &nbsp;    G &nbsp;   F &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;            C &nbsp; &nbsp; &nbsp;       B</b><br>Száz jajszó között is bíz<u>o</u>m vakon,<br><b>F &nbsp; &nbsp;&nbsp;      G &nbsp; &nbsp; &nbsp; &nbsp;         C</b><br>hitemet el nem adom.<br><b>&nbsp;C &nbsp;   G  F&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;           C &nbsp; &nbsp; &nbsp;       B</b><br>Rám törhet ezernyi baj, veszély,<br><b>F &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;          G &nbsp; &nbsp; &nbsp; &nbsp;         C</b><br>Isten így szól: "Ne félj!"<br><b>&nbsp;C &nbsp; &nbsp; &nbsp; &nbsp;         G B &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;          F</b><br>Mért <u>é</u>s kit?l félhetnék én?<br><b>&nbsp;C        &nbsp; &nbsp; &nbsp; &nbsp; G B&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;          F</b><br>Mért <u>é</u>s kit?l félhetnék én?<br><b>&nbsp;C &nbsp; &nbsp; &nbsp; &nbsp;         G B&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;          F</b><br>Mért <u>é</u>s kit?l félhetnék én<br><b>&nbsp;&nbsp;   G&nbsp;  F&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        C<br></b>az Ist<u>e</u>n tenyerén?</font></font></p>   jois az a dax<br>
++++
