= rokoneknak megyek halokartyat venni

:slug: rokoneknak_megyek_halokartyat_venni
:category: regi
:tags: hu
:date: 2006-01-06T12:46:55Z
++++
rokoneknak megyek halokartyat venni. kerdezi, h milyen opredszerhez. valaszolok, mondja, h nemtud adni. rancigalom a szemoldokom, erre kihoz 1dobozt, h o errol beszel. egy redhat 7.2es doboz. onkenytelenul is elmosolyodtam. 2.4.7es kernel, 2.2es kde (igen, abban az idoben meg okis a gnome elott irtak a kdet:)) 1.4es gnome, 4.1es xfree. vegul mondtam neki, h ok, akkor nemkell linux-compat legyen:)<br><br>btw kozben azert elegge felcukkoltak. a kartyat nemadtak ki azzal, h "pill, az sql server eppen mast csinal, nemlehet a tranzakciot megkezdeni". namost nemtom hogyvan ez, h de majdnem 3/4 orat csinalt mast. kozben utana levo pofat szolgaljak ki, vmi kulcsos zar kene neki a gephez. erre ajanljak, h szemben van 1 barkacsbolt (pf). es mindennek a tetejebe az uzlet kivan tapetazva 15colos tftkkel, amiken vmi 3d benchmark program fut - 7fpssel. no, remelem nemkell megint 1 ideig ilyen boltba menjek ;)<br>
++++
