= elore is elnezest, akik nem

:slug: elore_is_elnezest_akik_nem
:category: regi
:tags: hu
:date: 2005-04-08T14:47:48Z
++++
<p>elore is elnezest, akik nem beszelnek nyelvet:</p><p style="color: rgb(0, 0, 255);">The pope arrives in heaven, where st Peter awaites him. St peter asks to the pope who he is. <br>The pope : I am the pope. <br> St Peter : Who ? There's no such name in my book? <br> The pope : I am the representative off God on Earth. <br> St Peter : Does God has a representative ? He didn't told me... <br> The pope : but I am the leader off the Catholic Church... <br> St Peter : The Catholic church... Never heard of it... <br> St Peter : Wait, I'll check with the boss <br> </p> <p style="color: rgb(0, 0, 255);"> St Peter goes away trough heavens gate to talk with God. <br> </p> <p style="color: rgb(0, 0, 255);"> St Peter : There's a dude standing outside who claims he's your representative on earth. <br> God : I don't have a representative on earth, not that i know off... Wait, I'll ask Jesus ( Take his intercom and yells for Jesus) <br> Jesus : Yes father, what's up.... <br> </p> <p style="color: rgb(0, 0, 255);"> God and St Peter explain the situation.... <br> </p> <p style="color: rgb(0, 0, 255);"> Jesus : Wait, I'll go outside and have a little chat with that fellow. <br> </p> <p style="color: rgb(0, 0, 255);"> Ten minutes pass and Jesus reenters the room laughing out loud. After a few minutes St Peter asks To Jesus why he's laughing... <br> </p> <p style="color: rgb(0, 0, 255);"> Jesus : remember that fishing club I've started 2000 years ago.... It still exists.</p>
++++
