= ezek mar

:slug: ezek_mar
:category: regi
:tags: hu
:date: 2005-04-02T21:44:21Z
++++
ezek mar picit jobbak :)<br> <br> <div style="color: rgb(0, 0, 255);">- Kérem, csak addig vizsgáztasson, amíg a kettes megvan! - kéri a hallgató. Már egy órája vizsgázik, amikor a tanár megszólal:<br>- Na, adja ide az indexét, kolléga. Megvan a kettes.<br>- Phuuu. De nehezen ment!<br>- Azt meghiszem - így a tanár - fél órája még a jelesnél voltunk.<br><br>Vizsgán így szól a prof a diákhoz:<br>- Nos, kolléga, meg tudja nekem mondani, mit jelent az a szó, hogy<br>relatív permeabilitás?<br>- Pótvizsgát tanár úr, ha jól sejtem...<br><br>Az Egyetemen:<br>-Tanár Úr! Nem érdemlem meg azt az egyest, amit a dolgozatomra kaptam!<br>- Egyetértek, de sajnos ez a legalacsonyabb jegy, ami az egyetemen adható!<br><br>Egyetemen a vizsga elott megjelenik egy kissé kétes öltözéket viselo egyén. Az egyik diák így szól hozzá:<br>- Mi van, így jöttél vizsgázni?<br>- Nem, így jöttem vizsgáztatni!<br><br>Két egyetemista beszélget:<br>- Ha most kirúgnak, én öngyilkos leszek!<br>- Hülye vagy, ha én is így csináltam volna velem lenne tele a Farkasréti temeto.<br><br>Az egyetemen vizsgázik a hallgató. Mivel nem sokat tud az anyagról, eléggé makog. erre az oktató megszólal:<br>- Jöjjön közelebb kolléga úr!<br>A hallgató közelebb megy, de értelmes mondatot így sem tud kinyögni.<br>A vizsgázató folytatja:<br>- Jöjjön még közelebb!<br>A hallgató még közelebb megy, de a helyzet változatlan. Mire az oktató:<br>- Tudja mit kolléga úr, jöjjön legközelebb!<br><br>Ez az eset valóban megtörtént! <span style="color: rgb(0, 0, 0);">(szeretjuk az ilyeneket ;))</span><br><br>Hallgatót vizsgásztatják. Nagyon nem megy neki, minden kérdésre rossz választ ad. Tanár:<br>- Na jó, mento kérdés a kettesért. Hány kapcsoló van ebben a teremben?<br>A hallgató forgolódik, számolja a kapcsolókat...<br>Tanár:<br>- Páros vagy páratlan?<br>A hallgató gondolkozik, majd mondja:<br>- Páros.<br>A tanár elokap egy kapcsolót a zsebébol és így szól:<br>- Páratlan!<br>Erre a hallgató is elokap egyet a zsebébol és így szól:<br>- Páros!<br><br>Az egyetemi hirdetotáblán egy kézírásos hirdetés olvasható: "Fizika tankönyv áron alul eladó!" Másnapra egy kézírásos szöveg került mellé: "Engem érdekelne, de biztos, hogy nem használt? Egy reménybeli vevo" Harmadnap egy eltéro kézírással: "Megerosíthetem, abszolút biztos! A fizikaprofesszor."<br><br>Az egyetemen a diákok zárthelyit írtak. A prof kioszotta a kérdéseket, majd az óra végén beszedte a dolgozatokat. Amikor nekiállt javítani oket, észrevette, hogy az egyik diák egy ötezrest csatolt a papírjához, és ezt írta a válaszok helyett:<br>"Egy ezres minden osztályzatért"<br>Másnap aztán a vesztegetos diák megkapta a papírját, egy nagy egyessel, meg négyezer forint visszajárót<br><br>Közvéleménykutatók felmérést végeznek a különbözo társadalmi rétegek között, hogy ki szerint mennyi ido alatt lehet megtanulni kínaiul. Megkédezik a parasztbácsit, mire o:<br>- Szerintem egy egész élet is kevés rá.<br>A butikos szerint:<br>- Szerintem egy 3-4 év alatt jól meg lehet tanulni.<br>A menedzser válasza:<br>- Intenzív tanulással 3-5 hónap alatt.<br>Megkérdezik az egyetemistát is:<br>- Szerinted mennyi ido alatt lehet megtanulni kínaiul?<br>- Miért, holnap ZH?!<br><br>Tanár a diákoknak az egyetem filozófiaóráján:<br>- Az absztrakció olyan dolog, amit el tudtok képzelni, de nem érinthettek meg. Valaki tud ilyet mondani? Egy hátsó padsorból:<br>- Persze! A faterom autója.<br><br>Egy egyetemi kreatív író osztályt megkértek, hogy írjanak egy rövid értekezést, ami az alábbi elemeket tartalmazza: 1. Vallás 2. Királyság 3. Szex 4. Rejtély.<br>A díjnyertes esszé ez volt:<br>"Úristen! - mondta a királyno - Terhes vagyok! De vajon kitol?"<br><br>Elsos foiskolásoknak tart eligazítást a kollégium igazgatója:<br>- Nos, fiúk, a tiétek az elso szint, a lányok a második szinten laknak. A különbözo problémák megelozése érdekében mindenki az éjszakát a saját szintjén tölti. Az a szabály, hogy ha valakit eloször rajtakapunk a másik szinten, megbüntetjük 60 dollárra. Ha ez még egyszer elofordul, akkor már 120 dollár a büntetés, harmadszorra pedig már 180!<br>Hátulról egy hang:<br>- És egy féléves bérlet mennyibe kerül?<br><br>Egyetemi hallgató vizsgázik. Szakad róla a víz, iszonyú gondban van. A professzor kedvesen:<br>- Segíthetek egy kisegíto kérdéssel?<br>- Óóóó, igen professzor úr, köszönöm - így a diák.<br>- Nos?<br><br>Filozófia eloadáson a professzor logikai levezetést oktat.<br>Eload egy példát:<br>- Halotta már valaki Istent?<br>Néma csend.<br>- Látta már valaki Istent?<br>Ismét néma csend.<br>- Tapintotta már valaki Istent?<br>Megint néma csend. A professzor levonja a következtetést:<br>- Mivel senki nem hallotta, nem látta és nem tapintotta<br>Istent, ezért logikusan nem is létezik! Ekkor szót kér egy hallgató:<br>- Halotta már valaki a professzor úr agyát?<br>Csend.<br>- Látta már valaki a professzor úr agyát?<br>Csend.<br>- Tapintotta már valaki a professzor úr agyát?<br>Ismét csak csend. Erre a diák:<br>- Akkor az elozo logika szerint...<br><br>Mit mond egy frissen diplomázott munkanélküli bölcsész egy másik frissen diplomázott bölcsésznek aki már kapott munkát?<br>- Két Big Mac-et kérek!<br><br>Az ujdonsült egyetemista diák eloször megy haza iskolakezdés óta. Az anyja mondja neki:<br>- Kisfiam, levágtam két tyúkot. Mit fozzek belolük?<br>Erre a diák:<br>- Pálinkát, Édesanyám!<br></div>
++++
