= title_23

:slug: title_23
:category: regi
:tags: hu
:date: 2005-04-02T21:32:55Z
++++
ezeket most kaptam. elore szolok, farasztoak, felelosseget nem vallalok :)<br><br><div style="color: rgb(0, 0, 255);">Az amerikai katona &#337;rt áll az er&#337;d tetején.<br>Egyszercsak lekiabál: - Parancsnok, jönnek  az indiánok!<br>- Na és barátok, vagy ellenségek?<br> - Valószínüleg barátok, mert együtt jönnek!<br><br>- Miért mennek a sziámi ikrek Angliába?<br>- Hogy a tesó is tudjon vezetni!<br><br>-	Mi hallatszik ki az edz&#337;teremb&#337;l?<br>- A fitnesz.<br><br>- Hol hagytad az órádat?<br>- Mindig siet, biztosan már otthon van.<br><br>-	Miért van hátsóablak-f&#369;tés a Skodákban?<br>- Melegen tartja a kezed, amíg tolod.<br><br>Közlemény!<br>A munka jelképei megváltoztak. Az eddigi sarló/kalapácsot felváltja a <br>fagyi és a galamb. Aki nem nyal, repül!<br><br>- Mit&#337;l lila a Milkatehén?<br>- Szorítja a kolomp a nyakát.<br><br>-	Apu, már elmúltam 16 éves. Most már rúzsozhatom a számat?<br>- NEM KISFIAM!<br><br>-	Doktor úr, nem tudok aludni. Egész éjszaka le sem hunytam <br>a szemem.<br>- Ja, így már érthet&#337;.<br><br>Melyek a legnépszer&#369;bb üzletkozpontok Törökországban?<br>- Az Epi Centrum, és a Richter Skála.</div>
++++
