= Bringás ellenőrző lista

:slug: bringas-ellenorzo-lista
:category: bringa
:tags: hu
:date: 2014-05-22T08:41:18Z
image::https://lh4.googleusercontent.com/-_OtoqJm_WiY/U3fTdAMMciI/AAAAAAAAER8/4OMASQ1whSc/s800/[align="center",link="https://lh4.googleusercontent.com/-_OtoqJm_WiY/U3fTdAMMciI/AAAAAAAAER8/4OMASQ1whSc/s0/"]

A hétvégén a link:/blog/godollo-170.html[K100] útvonalát jártam
végig edzés céljából. A fenti képen a Vácrátót előtti egyik alattomos emelkedő
látható ;-)

Az emelkedő vége felé jutott eszembe, hogy itthon hagytam a kulacsom. Mivel
már olyan is előfordult, hogy az SPD-s cipőmet hagytam otthon (mikor nem
itthonról indultunk, hanem kocsival Mátrába, és csak ott bringáztunk), ill.
pár éve LGee a bukósisakját hagyta otthon (és kellett a Pelso helyszínén
vegyen egyet), gondoltam összeállítok egy listát, hogy mi az a 10 legfontosabb
dolog, amit semmiképpen nem érdemes otthon hagyni, ha dedikáltan bringázni
indul az ember:

. első és hátsó lámpa
. bukósisak
. cipő
. nyeregtáska (pótbelső, minimális mennyiségű szerszám, pumpa)
. kulacs
. kaja (ha a szervezők nem biztosítanak)
. kmóra
. kesztyű
. fényvisszaverő csík (hosszúnadrág esetén, hogy ne legyen olajos)
. láthatósági mellény (este, lakott területen kívül)
. láncolaj, GPS
. naptej / krém
. bringás nadrág / mez

Hátha ez segít, hogy a jövő heti Pelsora menet most ne hagyjunk itthon semmit. :-)

// vim: ft=asciidoc
