= DOCX import progressbar in LibreOffice Writer

:slug: docx-import-progressbar-in-libreoffice
:category: libreoffice
:tags: en
:date: 2014-03-22T15:54:39Z
image::https://lh5.googleusercontent.com/-sW_Ccet7HMU/Uy2hcmf7ZsI/AAAAAAAAEHg/IGwPJI6h6vE/s400/[align="center",link="https://lh5.googleusercontent.com/-sW_Ccet7HMU/Uy2hcmf7ZsI/AAAAAAAAEHg/IGwPJI6h6vE/w643-h518-no/"]

I'm sure in this case a few words are worth more than the above picture, so
let me describe what you see above. :-)

In case of opening an ODT, DOC or RTF document in LibreOffice Writer, you
already got some feedback on where the importer is, in case the process needed
more time than what you feel "instant". However, this wasn't supported for
DOCX.  According to `git blame`, I added this to my todo on 2012-10-29, and a
few months later also a
https://bugs.freedesktop.org/show_bug.cgi?id=58044[bugreport] was opened,
requesting the same, but up to yesterday, nothing changed.  However, now I've
implemented this on master, it'll be part of the 4.3 release.

Back to where I started, what you actually see there is when LibreOffice is in
the middle of the import process of the Holy Bible in DOCX format, which takes
around 12 seconds on my machine. One could say that speed up quite acceptable
for that amount of data, but with a progressbar, it's definitely better. ;-)

// vim: ft=asciidoc
