= 12huros gitar

:slug: 12huros-gitar
:category: zene
:tags: hu
:date: 2009-01-08T00:26:47Z

image::https://lh3.googleusercontent.com/f2fYdVWU0XsudYi5gMcUQwKflxxFuVHq2C6NTzdAD_XA1Nth91R9QoC-jOjn4p8PKOXjhmKT9wKGjVLkfZTTDYCksmE7gTWu6iYKPAiUuXGtvDOKMUt8NfH14CIxHWKYDz4mwo6guA=w640[align="center"]

hat ez valami felelmetesen nagyszeru talalmany :)

a mai gitarprobankon az egyuttesbol az egyik lany egy ilyennel allitott be (ois kolcsonbe kapta, de
azert lehozta erdekessegkeppen). persze ki akartam probalni, de az volt a feltetel h hangoljam be.
hat nem tudtam mire vallalkozok, leven a hurok kettessevel baromi kozel vannak egymashoz, szal
nemigazan arra van kitalalva, hogy egyesevel meg lehessen oket penditeni, igy aztan vagy negyed ora
alatt sikerult a project. de utana.. szal kb olyan elmeny mint hurcsere utan, es ezt ketszer.
iszonyu jo hangja van - bar http://en.wikipedia.org/wiki/Arpeggio[arpeggioban] kicsit szokni kell,
leven kevesebb hely van a hurok kozott. balkez szempontjabol meg persze erosebben kell fogni a
duplaannyi hurt es jobban szetszedi az ember kezet (nylonhuros gitar eseten a hurok feszitoereje
ilyen 40kg korul van, femnel duplaennyi, es egy ilyennek megtobb, 100kg korul).

ja es hangero szempontjabol se semmi, siman lekoroz egy kisebb erositot. ;)
