= Being international

:slug: being-international
:category: hacking
:tags: en
:date: 2009-02-27T00:51:54Z
++++
<p>There was a recent interview with the developers of UHU-Linux, which was the de-facto "Hungarian Linux" a few years ago here at Hungary.</p><p>The guys had a pretty closed approach and finally it seems they make money from products based on their distro - releasing something useful for the users for free is definitely not the number one task on their todo.</p><p>There were a couple of comments to the article, a few of them was about Frugalware, given that we are still the only distro where the origin is Hunagary and it's actively used outside Hungary as well.</p><p>In fact I just did a quick search, listing the last commit dates of each devel. Two of the Hungarian ones are pretty inactive. Both of them do other administrative tasks. (Buildserver / bugtracker hosting, etc.) But the rest is quite active, which was a surprise. I had the impression that lately we got some new French devels and once they got their git accounts, they got a bit less-motivated but this is simply not true. All of them (and this is true for the other non-Hungarian devels as well) was more or less active in the last month.</p><p>I think this is pretty straight-forward, even if the ohloh stat says the commit number (compared to last year) is sightly decreasing. This is a typical example: the commit number is not everything. I think this time last year we might be a bit more active overally, but that was because several devels (including me) spent a horrible amount of their free times on Frugalware, which is not something you can do for several years. Today we have a much stable devel base, increasing package maintainer community and yes, I'm happy with our current status. :)</p>
++++
