= children of men

:slug: children-of-men
:category: film
:tags: hu
:date: 2009-03-03T01:29:31Z

image::https://lh3.googleusercontent.com/csu_t-eMmzulwaF0sMLqIbPbxzb2JxP2G9e6JrMA4W4qlVSZfnCwokm5CIw6NgRi7MDFFEGm7oiL_cxkVoi_PVhevYS0eRfNTAhWcraFxf9H519VTRc1nWDN5ZaOdx6KTU1_Olp-CQ=w640[align="center"]

meg januarban volt http://index.hu/tudomany/biotech/medd220109/[egy indexes cikk], az a vicc (?),
hogy ez a film kb errol szol. marmint scifi, es az alapsztori az annyi, hogy a foldon mar kb 15 eve
nem szuletett ember, es akkor most mi lesz.

ami nem tetszett benne az az, hogy az egesz film olyan semmilyen. nem szorakoztato, de nincs is
mondanivaloja. van valamifele lezarasa, meg remeny is van benne, de az egesz olyan borongos.

filmes szempontbol persze egyreszt el tudom kepzelni, hogy mekkora melo lehetett egy csomo hosszu es
bonyolult akciojelenetet single-shotban felvenni (tehat hogy nincs vagas), de azert ez nem
ellensulyoz mindent.

amugy meg a ferfi foszerepet Clive Owen (sin city) viszi, meg feltunt meg par ismeros arc, mint
Chiwetel Ejiofor (kinky boots) es Julianne Moore (psycho remake), de semmi annyira kulonoset nem
alkottak, hogy erdemes lenne megjegyezni. felejtos.

(http://www.imdb.com/title/tt0206634/[imdb], http://www.youtube.com/watch?v=NikEQy1XxDE[trailer])
