= hands on scooter

:slug: hands-on-scooter
:category: zene
:tags: hu
:date: 2009-02-14T00:11:18Z

image::https://lh3.googleusercontent.com/v1407TE6nzH8y9lQLp7Y0KexxI3qgU5Wn-otS2VqWS4PlsqavQ4UT_xlwbleV7NLhQ2gxF4jB3HuBqk7A26B-uG3hz30SnVDrZaIT1yna7hRlvnQ6aICowkNNmVn0WU3lpA2NP700A=s240-p-k[align="center"]

szoval lassan tobb mint egy honapja, januar nyolcadikan jelent meg a scooter szamainak
feldolgozasabol kiadott gyujtemeny, a hands on scooter. ertelemszeruen a mufaj a legtobb esetben
jelentosen elter, de mivel az eredeti szamokert rajongok, igy a feldolgozasok nagyresze is tetszett.

a korongon 12 feldolgozas talalhato, termeszetesen csupa olyan trackbol amik eredetileg nem
feldolgozaskent keszultek, hiszen eleg vicces lenne a feldolgozas feldolgozasat kiadni. ;)

. jump that rock. ez modositas nelkul kerult a gyujtemeny elejere, leven a status quoval eredetileg
is egyutt keszult a dal.

. egy weekend feldolgozas, eleg drogosra sikeredett. igy aztan ha elkepzelunk par erosen betepett
alakot az utcan fel-le jarkalni zombikent akkor az eredmeny nemnagyon ter el attol amit a bloodhound
gang kihozott ebbol az alkotasbol. ;)

. hogyan keszitsunk a how much is the fishbol nemet rapet? hat igy. ez a nemet rap tema igy
onmagaban is iszonyatosan beteg. :]

. egy move your ass feldolgozas, de hp mc szovegeit teljes mertekben lecsereltek. eleg mokas az
eredmeny, bar nem mondanam, hogy sokkal jobb az eredetinel.

. mivel a cimet valtozatlanul hagytak, egyszeru volt rajonni, hogy egy hyper hyper feldolgozas
kovetkezik. a szoveg a zene felett vegig generalt, bar legalabb nem microsoft sammel. ;)

. egy i'm raving feldolgozas, az elso. mert lesz meg egy masik is, kesobb.

. ugy indul, mintha a wicked up (igen, a "nyalas") lenne, de aztan kiderul, hogy az aiii shot the dj
adja a szam alapjat. fokepp a kiserohangszereket manipulaltak, meg belevittek par uj dallamot, a
szoveg teljesen az eredeti.

. ez valami felelmetesen stilusos. friends, de ilyen kankanos stilusban, tangoharmonikaval, meg
nemetul. kesz. :D

. faster harder scooter, ahogy azt egy musicalban eloadnak. otletes. :)

. mig a hatos szam alatti i'm raving eleg rockos lett, itt meghagytak a mufajt, es tovabbra is
elektronikus hangszerek hangzanak fel, bar jelentosen megkavartak az egeszet. nekem a masik
feldolgozas jobban bejon. "hamar hozzanyulunk, nyuljunk hozza nagyon." ;)

. nessaja. az egesz ugy indul, mintha karaoke lenne, de nem a szoveg hianyzik hanem a szovegen kivul
minden mas, es az is csak nanazva. ;) aztan folytatas eleg elvont..

. itt szinten kell egy ideig figyelni mig rajon az ember, hogy mit is dolgoztak fel, gyakorlatilag a
one es a maria dallamait mixeltek ossze, az eredmeny pedig termeszetesen kivalo. :)

osszegzes? a 12 remixbol 8 volt olyan amiben valami megfogott, igy osszessegeben egesz jol sikerult
szerintem a valogatas.
