= kiberiada

:slug: kiberiada
:category: konyv
:tags: hu
:date: 2009-02-15T00:53:26Z

image::https://lh3.googleusercontent.com/yMVpfCchpC6U4wsVBBnHtHM8p6VJtHWfhU7ZUNjMHZPJGcimhEG8kRwhtDfjk9tnq-_N5J5LeqwpNqXYAb7QgMyT7fsAxfSj4lxIEO4zIb99duHTEWMW7GhQRnUvkKKoLp1GPmR-bw=w2400[align="center"]

mint a kepen is lathato, az elkoveto Lem bacsi. a konyvet eleg sok ideig olvastam, pedig nem
kulonosebben hosszu (~ 400 oldal), viszont nem is hagyomanyos ertelemben vett scifi. sokkal inkabb
mese az egesz. az eleje kevesbe osszefuggo mesekbol all, a masodik resze pedig trurl és klapanciusz,
a ket "mernok" kalandjaibol all. hogy kevesbe legyen kovetheto a tortenet, nehanyszor elkoveti a
mar-mar mester es maragitat lekorozo "tortenet a tortenetben" effekt egymasra halmozasat. ilyesmi,
hogy "trurl meseli, hogy itt es itt jart, ahol bemutatott ennek es ennek a kiralynak egy gepet",
majd a gep elkezd meselni, aztan abban jon egy alom, stb. :)

szoval kicsit nehezen kovetheto ha villamoson olvassa az ember vagy hasonlo. ami meg a forditast
illeti, valami zsenialis, tele van szoviccel az egesz sztori, es gondolom nem volt tul egyszeru a
magyarban visszaadni ezeket a lengyel szovicceket, megis sikerult.

boobaa link:|filename|/2007/stanislaw_lem_visszateres.adoc[kerdesere] reagalva azert a "normal"
tortenetei (mint pl a visszateres) nekem jobban bejottek, de persze ez se rossz.
