= lady in the water

:slug: lady-in-the-water
:category: film
:tags: hu
:date: 2009-01-15T03:36:08Z

image::https://lh3.googleusercontent.com/o8LBuELL3zpZhsyEEyRnjtAPaHs53Eopy0mzDwAWVelbzddAP1r-hkR8KVkS2W_GgoKevgpwPId7fcgEwqArEs8ccHjgvbtYQpB3RyZQhahoUGxmf1TQaLimv93cQFrsVOD47eJUeg=w640[align="center"]

ez nem jott be. szegeny http://kemenczy.hu/[k]-t el kell szomoritsam, ugytunik nem egyezik minden
szempontbol a film-izlesunk.

igazabol ha van egy kis eszem, es elobb utanananezek, hogy Shyamalan redezte, akkor nem meglepo. :)
eloszor lattam tole a falut, link:|filename|/2007/a_falu.adoc[az meg jo volt]. aztan jott a (persze
idoben korabbi) hatodik erzek, az link:|filename|/2007/hatodik_erzek.adoc[nem tetszett] - bar igaz,
annyibol erdemes volt megnezni, hogy Bruce Willis mekkora jo arc mar, hogy tud nemcsak lovoldozoset
jatszani.

itt is ez az utobbi a szitu, csak eppen Bruce Willis nelkul. noi foszerepben a falubol az egyik
szinesz, aki kb u.ugy jatszik, de ott vakot jatszott, itt meg nem. a ferfi foszereplo elvileg a
paycheckbol ismeros kene legyen, de nem az. a film kozponti temajat kepezo szorny kb olyan, mintha
en csinaltam volna: annyira lenyugozott, hogy azon gondolkodtam, hogy biztos inverz kinematikaval
mozgatjak a vegtagokat. :)

ja es van hozza meg valami kinai mese is - utalom a japan/kinai meseket.

(http://www.imdb.com/title/tt0452637/[imdb], http://www.youtube.com/watch?v=An7r24E5pFw[trailer])
