= piaf piaf

:slug: piaf-piaf
:category: zene
:tags: hu
:date: 2009-01-10T23:48:54Z

image::https://lh3.googleusercontent.com/L-GU10_QtFaiNFeFdOkt84PrQDHQprqi87-ROLFDEIAKcMDXvpejJmxbRkygf96ei_kz_7IoNnIiUBK713FisNyxkoXVWIUIvX7xAUm4V8rlKJgm-YrVHLrsk8QEQzFSUpEG2VPXDQ=w640[align="center"]

zene, de igazabol talan valahol a musical meg a tanceloadas kozott. a cimben levo linken el lehet
hozza olvasni a hivatalos dumat, szemely szerint inkabb azt mondanam, hogy a darab ugy viszonyul a
kozismerten abszurdnak es modernnek titulalt godot-ra varva-hoz, mint egy scooter koncert egy
operaeloadashoz. huh? igen. :) bemegy a user es azt hinne, hogy akkor most egy,
http://hu.wikipedia.org/wiki/Edith_Piaf[Piaf] eletet feldolgozo eloadast fog latni. hat egy turot.

csak, hogy nehany elrettento peldat emeljek ki:

- a darab ugy kezdodik, hogy a szineszek kulonosebb jelmez nelkul be-be jonnek a szinpadra, az egesz
  olyesmi mint a http://www.imdb.com/title/tt0070239/[szupersztar] elejen mikor poloban meg
  farmerben megjonnek a szineszek, es ott kezdenek el feloltozni a forgatashoz.
- mikor ez mar vagy 20 perce megy, akkor megnyugtatjak a kozonseget, hogy "mit varnak, a tortenetet?
  ja, az nincs". ok, tehat akkor nezzuk mi johet meg ;)
- az egyik szamot mikor eneklik akkor bevonul vagy 7 ferfi szinesz, gatyara vetkozik, ezutan
  felvesznek noi ruhakat es az egyik ilyen kiherelt hangon elkezdi enekelni az egyertelmuen noi
  hangmagassagra irt dalt

persze az optimizmus vegtelen, es tenyleg volt benne par mokas dolog.

- egyreszt volt benne egy csomo piaf szam, amit - legalabbis zeneileg - ugytunik modositas nelkul adtak elo.
- az egeszet a zenekar eloben kovette, nem cdrol toltak be a lewarezolt karaoke verziot ;)
- balettnek szerencsere nem nevezheto, de ilyen akrobatikus akarmiket eleg sokmindent csinaltak, pl
  az egyik no ugy tolta a szolojat, hogy felfekudt valami asztalra, fejjellefele bedontottek
  45fokban, aztan azzal rohangaltak fel-le, a csaj meg szemrebbenes nelkul enekelt :)

hat szoval nemtom. talan meguti az "annyira baromsag, hogy mar jo" kategoriat, de igazabol sztem nem
eri meg azt a kidobott 3 orat / 2.2khufot, ami elment miatta. de legalabbis ovatosan mielott valaki
gondolkodas nelkul jegyet vesz ra :P

ja es a fenti kepen lathato Telkes Peter kisertetiesen emlekeztet
http://www.imdb.com/name/nm0000160/[Ethan Hawke]-ra, but maybe it's just me.
