= the man from earth

:slug: the-man-from-earth
:category: film
:tags: hu
:date: 2009-01-30T08:40:19Z

image::https://lh3.googleusercontent.com/QdeBCQNflCd7myxGwGfg_c7SlX4WxBRZ-q5Mh7pyT-Xaq2pY9dY4Sh4cgmod2_OzCl9I9AjpiYr_vcK6Y1lxRbeyIwdbWJhBEwKYJX43NIiyDkW2JXS-Qv1NacGsf46qERGxQFahOg=w640[align="center"]

magyarul azthiszem oslako neven fut. nem egy akciofilm. vegulis scifi, de ugy, hogy az egesz
cselekmeny egy szobaban, meg - esetleg vegyuk meg hozza azt - a haz elotti kis kertben jatszodik. a
jellemek egyenkent aprolekosan kidolgozva, a melyen vallasos, a folyamatosan kotekedo, a cinikus, a
fenyegetozo, stb. :)

aki szereti a muveszfilmeket annak be fog jonni.

a foszereplo David Lee Smith a fight club-bol mar ismeros, a tobbiekre meg jellemzo, hogy
nagyreszuknek meg a vezetekneve sincs kidolgozva. mert minek. a lenyeg, hogy egy igaz-hamis kerdest
hogyan itelnek meg, es ohatatlanul mi is a tortenet reszeveve valunk azzal, hogy hol csak nevetunk,
hol meg pislogva hallgatjuk az erveleseket.

talan leginkabb a 12 duhos emberhez tudnam hasonlitani, bar ez nem annyira regi.

ja es pls valaki mondja mar meg, hogy ennek a trailerehez miert a "best sex ever" cimu video az elso
related? :P

(http://www.imdb.com/title/tt0756683/[imdb], http://www.youtube.com/watch?v=njU5CsrYfKM[trailer])
