= - volt ma ez a

:slug: volt_ma_ez_a
:category: regi
:tags: hu
:date: 2004-07-25T23:09:43Z
++++
- volt ma ez a meló<br>- jól ment, csak az alaplapi ide vezérl? volt hibás, és be kellett bizonyítanom<br>- de összejött. ja aztán meg workaroundolni, h felmenjen a rendszer<br>- mert nyilván ott helyben, akkor kellett feltenni a rencert<br>- javítani meg jó esetben holnap be viszik a szervízbe :D<br>- de viszont jófejek voltak, mert nemcsak az utazási kölcséget fizették hanem arra is fizették a 400as órabért :D<br>- so dolgoztam 8at és 14et fizettek :D<br>- kedvesek, btw volt is mit jóvátenni<br>- odahívnak, h tessék linuxot telepíteni, mikor hibás az alaplap, ne mondják már, h nem tudták<br>- viszont aludtam oda 3 meg vissza 3 órát, mondjuk tegnap éjszaka úgyis csak 3at :D<br>- azért olyan keveset, mert 10-18ig nem voltam itthon, még 10edike el?tt letárgyaltuk, h 25én megyek le, és szombat reggel jutott eszembe, h mindent megbeszéltünk, csak nincs meg a telefonszáma és nem tudják melyik vonattal jövök, és én meg nemtom hova kell menni a vonatállomásról<br>- szivás. soval reggel megírtam az email, h wtf, és hajnali 2kor válaszolt, tehát 2ig én aszittem, h nem m1ek le ma :D<br>- mivel 3/4 7kor ment a vonat, 6kor kellett indulni, 5kor kelni - az már kérdés, h 6:20kor indultam el, a 6:40kor induló ichez, mert 5-6ig kerestem a cdket, amir?l telepíteni fogok :D<br>- mert azt is még 10.e el?tt letöltöttem el?re, aztán elhagytam valahol :D<br>- aztán lerohanok a délibe, persze pénzt nem vittem magammal, so pénz kivesz, hosszó sor kiáll, 38kor felszállok a vonatra :D<br>- visszafelé majdnem u.ezt eljátszottam :D<br>- kerestem 1 templomot, ahol van 5kor mise, a templomot elmagyarázták nagy immel ámmal az irodába, h hogyan kell oda menni, és a templomból meg kiderült, h negyedóra buszozás a p.u., nekem meg volt 20p az idulásig, de végül elértem :D<br>- FrugalWarehez nem nyúltam. a 10-18ig terjed? id?szakot leszámítva imho ilyen legalább március óta nem volt :D
++++
