# https://about.gitlab.com/2016/04/11/tutorial-securing-your-gitlab-pages-with-tls-and-letsencrypt/
pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r .well-known * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
