DO_RECURSIVE = @ for i in $(SUBDIRS); do $(MAKE) -C $$i || exit 1; done

SUBDIRS = gpg projects resume

all:
	+$(DO_RECURSIVE)

sync: check
	git add -A
	git commit -m "Autogenerated blog for v$(shell cd ../rejourn/in/; git describe --tags)"
	cd ../rejourn/in; git push
	git push

backup:
	(cd ~/mnt/backup/git/staging.vmiklos.hu/ && rsync --delete -avP $(PWD)/../ .)

restore:
	(cd ..; rsync -avP --delete ~/mnt/backup/git/staging.vmiklos.hu/ .)

check:
	$(MAKE) -C ../rejourn/in check

server:
	python3 -m http.server
