run:
	python3 -m http.server

sync:
	cd ../pelican && make remote && git push
	git add -A
	git commit -m "Autogenerated blog for v$(shell cd ../pelican/; git describe --tags)"
	git push

404.html: 404.md Makefile
	pandoc -s -o 404.html 404.md
