DO_RECURSIVE = @ for i in $(SUBDIRS); do $(MAKE) -C $$i || exit 1; done

SUBDIRS = gpg projects resume

all:
	+$(DO_RECURSIVE)

sync:
	git add -A
	git commit -m "Autogenerated blog for v$(shell cd ../rejourn/in/; git describe --tags)"
	cd ../rejourn/in; git push
	git push

server:
	python -m SimpleHTTPServer 8000
