= xmlsec improvements in LibreOffice 5.4

:slug: xmlsec-lo54
:category: libreoffice
:tags: en
:date: 2017-05-17T09:09:59Z

This post summarizes the plumbing work around ODF/OOXML digital signatures
that I did on LibreOffice master after the 5.3 branch-off up to now. The big
thing is the
https://gerrit.libreoffice.org/gitweb?p=core.git;a=commit;h=ad319fdfcaaa6092ea1ff76935e088c5122e0d2e[integration]
of the libxmlsec 1.2.24 release. Among other things, this contains 2 larger
changes that I contributed upstream triggered by the needs of LibreOffice:

- The link:/blog/xmlsec-nss-ecdsa.html[ECDSA-SHA256 feature] is something I
  already mentioned, but I did not bother to backport the SHA1 and the SHA256
  part, so those now arrived to LibreOffice as well.
- xmlsec's `XMLSEC_KEYINFO_FLAGS_X509DATA_DONT_VERIFY_CERTS` flag (while
  verifying signatures) was there, but its behavior was not clear (neither
  for https://github.com/lsh123/xmlsec/pull/78[nss] nor for
  https://github.com/lsh123/xmlsec/pull/79[mscrypto]). I've changed it to be in
  sync what you have in other commands to avoid certificate validation (like
  `wget -k` or `curl -k`), which means as a next step there will be one less
  xmlsec patch in LibreOffice that prevents us from using xmlsec from the system
  on Linux. (Adding tests also detected that in the nss case not using that flag
  also didn't do verification by accident, this is now fixed as well.)

After the release I also noticed that creating signatures on Windows
https://www.aleksey.com/pipermail/xmlsec/2017/010143.html[was broken], this is
now fixed on xmlsec master and also backported to LibreOffice.

All this is available in LibreOffice master, towards 5.4.

// vim: ft=asciidoc
