= btLr text direction in Writer, part 3

:slug: btlr-text-direction-in-writer-3
:category: libreoffice
:tags: en
:date: 2019-06-13T16:49:16+02:00
:status: draft

I already wrote about the btLr text direction in the context of Writer table cells as a result of a
https://www.collaboraoffice.com/[Collabora] hack week (link:|filename|/2019/hackweek-2019.adoc[part
1], link:|filename|/2019/btlr-text-direction-in-writer-2.adoc[part 2]). The next step in this jurney
is btLr text direction of Writer Text Frames, and building on top of that: DOCX Text Boxes. Here is
a series of screenshots showing the result:

.tdf104353.docx, baseline
image::https://lh3.googleusercontent.com/mHrS3KHuLf4tnWOZTw83jJiF3bJ6Ti8fiHXSJlqBFwrdDEpCdS9m_mTfHQPhOXNbZ5atXkagrGO7fSAJPSUo9pEm73UMr_kT6oVwOLCjZwxR9NB_EsLxHUXmUtUiSq0Zr-C0_TNLMg=w640[align="center"]

.tdf104353.docx, current
image::https://lh3.googleusercontent.com/haH8Tu0CiUQ9OHWn3Pc9PJ8pP6fEwpGZtrtYUrtkYLYH_BLnLknIA5hBruslE2XIJnuoFjGxYhuFj3GqH4Peu2slIH83ss9vIPMXSn_E5q2Lr80cz2_h7rPuI1DRgJYou6AaOQzAaw=w640[align="center"]

.tdf104353.docx, reference
image::https://lh3.googleusercontent.com/ZZKDSlC3-VmuVbvvR7nlsNUi6A-mWAj6wJgg2TMzBMg0MQ01kN0iwnHvw_16GDopYT2hNuJwUKWZ5ugbg6TjkJWJ_V5rHwv2fpwumuGLLF29hYYtEPOb0v2en5UHY5p8kHyxTWtYZA=w640[align="center"]


I fixed the following problems since the last blog post on this topic:

. http://cgit.freedesktop.org/libreoffice/core/commit/?id=0013f21ecd918e0541f165c3526a58f42dd75481[tdf#124344 sw btlr writing mode, DOCX import: fix vertical alignment]
. http://cgit.freedesktop.org/libreoffice/core/commit/?id=8072a926da2a02dfaf3fa848a2976634641a594f[tdf#124521 sw btlr writing mode render: fix paint rectangle on scroll]
. http://cgit.freedesktop.org/libreoffice/core/commit/?id=ff17478e069cc82681df62514876c06365dd5cd6[sw btlr writing mode: implement DOCX shape import for tbrl]
. http://cgit.freedesktop.org/libreoffice/core/commit/?id=cd2a7acd789297e613424a59b2fe24cedd9a72b6[sw btlr writing mode: implement ODF filter for textframes]
. http://cgit.freedesktop.org/libreoffice/core/commit/?id=8a26e4b26f0153fb8ca5da880ee4aa44748ee4df[sw btlr writing mode: implement layout for fly frames]
. http://cgit.freedesktop.org/libreoffice/core/commit/?id=52e47276694575f119192f6ddafa69ec7a7eb6b4[sw btlr writing mode: implement UI for fly frames]
. http://cgit.freedesktop.org/libreoffice/core/commit/?id=ad96f6f378a9fce11c2f7d9ad39a8203189444e3[sw btlr writing mode: fix btlr <-> tbrl switch for fly frames]
. http://cgit.freedesktop.org/libreoffice/core/commit/?id=9c945cdbe170104cbacafa2c37babec5210b9ca2[sw btlr writing mode: DOCX drawingML import for fly frames]

All this is available in LibreOffice master (towards 6.4), so you can try it out right now, if
interested.
