= btLr text direction in Writer, part 2

:slug: btlr-text-direction-in-writer-2
:category: libreoffice
:tags: en
:date: 2019-04-15T09:13:19+02:00

I already wrote about the link:|filename|/2019/hackweek-2019.adoc[btLr text direction] in the
context of Writer table cells as a result of a https://www.collaboraoffice.com/[Collabora] hack
week. This is meant to be an update to present what happened in the past 2 months. Here is a video
showing the results:

.Before / after screen recording for the below mentioned changes
image::https://lh3.googleusercontent.com/RnesyNWGxQM4R255yFIVx_6_ft0Qu38rE10k22dblhzB8J5IG-W5RfNdncu_xtwYfXe-D7GtX7CJVKtspcQVflW2YiWm1EWf9ed3IqH4_bw-ElSKqE2OR4mRsCUcaJrSf61xy4Me_g=w640[align="center",link="https://youtu.be/79z9XDdH4x8"]

I fixed the following problems since the last blog post on this topic:

. http://cgit.freedesktop.org/libreoffice/core/commit/?id=31f896bb6ef922cf4250c6b971fb9d24a60592b5[sw
  btlr writing mode shell: fix up/down cursor travelling]
. http://cgit.freedesktop.org/libreoffice/core/commit/?id=8ae5a98852c2f3d87d6efff598f0c7d54df835d3[sw
  btlr writing mode shell: left/right cursor travelling, fix dest para]
. http://cgit.freedesktop.org/libreoffice/core/commit/?id=404bfc6f78549d16de193794960a9c9ab7604511[sw
  btlr writing mode shell: left/right cursor travelling, fix vert pos]
. http://cgit.freedesktop.org/libreoffice/core/commit/?id=2f83055cdbd915d5036a7b4374b4ad10e6efc65f[sw
  btlr writing mode shell: fix cursor selection]
. http://cgit.freedesktop.org/libreoffice/core/commit/?id=4c5d0e4822dcd0c6c9397a45e3afb66d53ebaafc[tdf#123943
  sw btlr writing mode render: fix text portion background]
. http://cgit.freedesktop.org/libreoffice/core/commit/?id=89e5b431d468745da3a1eff14d48296107b9101b[sw
  btlr writing mode: implement DOC filter]
. http://cgit.freedesktop.org/libreoffice/core/commit/?id=e651a4f45b310f9890ffbf712b9970d4c452ecec[tdf#124261
  sw btlr writing mode render: fix invalidation rectangle]
. http://cgit.freedesktop.org/libreoffice/core/commit/?id=b62bfda66c1499806bfa35c26fdc05f76f8a4db2[sw
  btlr writing mode: implement RTF export]

All this is available in LibreOffice master (towards 6.3), so you can try it out right now, if
interested.
