= Bottom to top, left to right writing direction in Writer conference talk

:slug: libocon2019
:category: libreoffice
:tags: en
:date: 2019-09-12T11:27:58+02:00

image::https://lh3.googleusercontent.com/7A-ATV-MLBkNG6T7cX7kmq2bd7cgsmUs81plgl1ZXlbQIhonNNWZDFMHB5iMPr3NhtT5S_-TO3HTPLh8mqKfUduGDGEZg0LRwRMZO5POBbqn5133-TDo0FipATD9_hlfFe7J19g9Mw=w640[align="center",link="https://speakerd.s3.amazonaws.com/presentations/d34ea52e0ebc4d2f898b246ef786f741/btlr-locon-almeria-2k19.pdf"]

Yesterday I gave a
https://conference.libreoffice.org/2019/program/schedule/sept-11th-wednesday/[Bottom to top, left to
right writing direction in Writer] talk at the LibreOffice Conference 2019. The room was
well-crowded -- perhaps because it was on the first day and in the largest room. ;-)

It contains some details which are not available in previous btLr blog posts, like what natural
languages use this direction, how to replace real-world clocks without breaking compatibility and
more!

I expect quite some other slides from other Collaborans and the wider community will be available on
http://planet.documentfoundation.org/[Planet], don't miss them.

You can get a snapshot / demo of Collabora Office 6.2 and try the presented feature out yourself
right now: https://www.collaboraoffice.com/collabora-office-latest-snapshot/[try unstable snapshot].
Collabora is a major contributor to LibreOffice and all of this work will be available in TDF's next
release, too (6.4).

// vim: ft=asciidoc
