= Continuous endnotes in Writer

:slug: sw-continuous-endnotes
:category: libreoffice
:tags: en
:date: 2019-10-21T10:24:32+02:00

Writer now has a new "continuous endnotes" compatibility setting in its layout, allowing rendering
endnotes in a way which is closer to what Word users expect.

First, thanks https://tu-dresden.de/[TU Dresden] who made this work by
https://www.collaboraoffice.com/[Collabora] possible.

Here is how it looks:

.Writer, new ContinuousEndnodes layout flag enabled
image::https://lh3.googleusercontent.com/g4kmuKduOm-Xc5sHH5oBx9y-U8S6hK5pgamrLxG-5fM9XCRJwMJFEPKxWXrG6IzEQLVpHdxCHI0c45EjDax02SpDbIzyQjZvUd-gsvpTWlkgZ0p3Y5-FDXARIPggF0KyIwG1AFwoiQ=w640[align="center"]

.Reference rendering
image::https://lh3.googleusercontent.com/dlUGc11qUKVvvkKXh5mhj9BlEw4bLxgKxW_t3pNAAu2rnuWuIrFtWdlKk-8nadbSur8CaDe-CIUNJiSJlQSTvA22Q89TkY-uRsdJH3EKX6RcyUJsr-W5YqJrVqaM4KgXAIDPxPXPvg=w640[align="center"]

.Writer, old separate endnote page layout
image::https://lh3.googleusercontent.com/odkN2eqFxYthY7qhxHwStIlodTZJmcUa5wzh6p74PWPT6jKtsAmAvZyNzTjwff_CrDm5AtTcdAq_Rw2QyMNQN1Xr_ypIYL_cEZ3g1DRJof9em6acQ1fxrNQWsx_LxUmBhmu4TkTmPw=w640[align="center"]

What you can see is that endnotes unconditionally start after the end of the document content in
Word, while endnotes are unconditionally on separate endnote pages in Writer. The new
`ContinuousEndnotes` layout compatibility flag in Writer allows rendering endnotes the Word way.

This new flag is enabled by default for DOC files, disabled otherwise.

All this is available in LibreOffice master (towards 6.4), so you can try it out
http://dev-builds.libreoffice.org/daily/master/[right now], if interested.
