= ctags vs override/SAL_OVERRIDE

:slug: ctags-sal-override
:category: libreoffice
:tags: en
:date: 2015-06-29T09:29:56Z

image::https://lh3.googleusercontent.com/-9Hd40EVT8aw/VZBhBTZQdTI/AAAAAAAAFyM/AfymfTqKDFw/s0/[align="center"]

If you use http://ctags.sourceforge.net/[ctags] to help your LibreOffice
development, there are already good descriptions for that -- e.g. for vim
there is one https://wiki.documentfoundation.org/Development/Vim#ctags[on the
TDF wiki].

What was problematic is that since $$C++11$$, `override` is a valid keyword
after a member function declaration, and we have our `SAL_OVERRIDE` macro that
I
http://cgit.freedesktop.org/libreoffice/core/commit/?id=3891d323cdc3c03154f5682baaeaa4b2ef015a63[added]
to be able to use it before all our supported compilers recognize it.
Unsupported parsers include ctags, so if a member function have SAL_OVERRIDE,
ctags only indexed the definition, not the declaration.

I created patches to fix these problems in ctags, the
https://sourceforge.net/p/ctags/bugs/367/[override one] is probably
interesting for all $$C++$$ projects, the
https://github.com/vmiklos/ctags-svn/commit/ef53a231db5b428585324f266072b884e17bae52[SAL_OVERRIDE
one] is LibreOffice-specific.

The hope is that the later will go away in the long run, so it won't really be
a problem that ctags do not recognize that macro out of the box. :-)

// vim: ft=asciidoc
