= A tizennegy karatos auto

:slug: a-tizennegy-karatos-auto
:category: konyv
:tags: hu
:date: 2010-05-24T02:06:03Z

image::https://lh3.googleusercontent.com/0X57szEegQeXIOrVtcNHTFB_aE3LsVkRfTbvUL6xzgGtpo48rf1SFlV_Mr0ckXLY9LOR3KlArOaJZuOOAnSrg-224lNluNr417Gg_P-M-JxzuvSPc_SzQUn7GbNc3CWxBDOS4cfK4A=w640[align="center"]

Valami nem-scifire fajt a fogam, hat e mellett dontottem. Nem volt semmi kulonosebb oka, hogy pont
ezt, csak valami Rejtot kerestem, leven link:|filename|/2008/vesztegzar-a-grand-hotelben.adoc[ez]
nagyon tetszett annak idejen.

Termeszetesen nem csalodtam, alljon a szokasos modon itt par kedvenc resz:

[quote]
____
-- Gorcsev Iván vagyok, foglalkozásomra nézve huszonegy éves, a Naszja Gorjodin-beli báró Gorcsev
cári kamarás testvéröccsének a fia. Atyám kapitány volt a gárdában, és nagybátyám a Jusztveszti
Versztkov kormányzóság katonai parancsnokaként védte Ogyesszát a fellázadt hadiflotta ellen.

Mindebből egy szó sem volt igaz. De egészen fiatal lánykák és öreg tudósok hiszékenysége állítólag
korlátlan. A tanár feltette csíptetőjét.
____

[quote]
____
Még borotválkozni is akart. Az ember ne álljon be akárhogy a légióba. Törülközőt kötött a nyakába és
kinyitotta a mindennel felszerelt, hatalmas gardróbszekrényt.

Ám ekkor legnagyobb csodálkozására az alsó polcról Vanek úr esett ki a padlóra.

-- Uram! Miért nem kopog az ajtón, ha benyit valahová!

-- Ezt a lakosztályt én bérlem!

-- De a szekrény az én magánlakom! My house is my castle!

-- Vanek úr! Én a mennyekből hullottam alá.

-- Mégis én ütöttem meg magamat!
_____


(http://bookline.hu/product/home!execute.action?id=2100532541&type=10[bookline])
