= googlecl and geeqie

:slug: googlecl-and-geeqie
:category: frugalware
:tags: en, hacking
:date: 2010-08-02T12:50:45Z
++++
<p>I recently tested two new Frugalware packages.</p><p>googlecl is a commandline utility, I wanted to try it out as it has browser-based authentication, which is supposed to be compatible with Google Apps, while the API-based method used by picu is not. To make it short, in case you are in a directory containing photos for an album and you just want to upload all of them to an album named after the directory name, you need:</p><p><pre>
google picasa create --title $(basename $(pwd)) *.jpg
</pre></p><p>The other package I recently tested is geeqie, it's a replacement (see history <a href="http://geeqie.sourceforge.net/">here</a>) for gqview I usually use to watch a lot of photos in a directory. And yes, they seem not to break any of the nice feature of the old gqview project, good work! ;)</p><p>Update: there is a <a href="http://code.google.com/p/googlecl/issues/detail?id=170">patch</a> to add sync support, it's usage:</p><p><pre>
google picasa post --title $(basename $(pwd)) --sync *.jpg
</pre></p>
++++
