= Hackerspace Budapest

:slug: hackerspace-budapest
:category: geek
:tags: hu
:date: 2010-08-19T22:48:55Z
++++
<p>A cimben emlegetett helyrol mar tobbszor hallottam <a href="http://twitter.com/dn3t">dnettol</a>, de idaig nem allt modomban szemelyesen megtekinteni <a href="http://hspbp.org/fogashaz">a helyet</a>. Ma <a href="http://hspbp.org/tiki-calendar_edit_item.php?viewcalitemId=202">tartott</a> viszont Erlang temaban workshopot, igy mar megvolt a szukseges motivacio, hogy elkarikazzak odaig.</p><p>A hely zsenialis, professzionalis bringatarolo fogadott, majd onnan felfele egy igencsak lepusztult, de a gyerekkori kuckokat felnottes stilusban megvalosito latvany fogadott, idealis terep arra ha valaki otthonrol elvonulva nyugodtan akar valamit butykolni.</p><p>Az eloadason kivul legjobban a <a href="http://hspbp.org/hack2o">viragontozo</a> tetszett:</p><p><pre>
22:36 &lt;@dnet&gt; a rossz szkennert ingyen kaptuk egy cegtol, a csovek loot
                    UTP kabel boritasok, a virag ajandek, a vodor meg a
                    space kifestesekor kerult be
</pre></p>
++++
