= Memory upgrade to 3G

:slug: memory-upgrade-to-3g
:category: hacking
:tags: en
:date: 2010-02-26T01:45:31Z
++++
<p>So my netbook had 1G of ram so far and I was happy with it. Then I started to play with virtual machines and it turned out that the bottleneck of it is the small memory I have. So I just bought a 2G ram module, and at this point things started to be weird. Given that the system booted up and <em>almost</em> everything worked properly, I did not really had an idea. I thought it's a SW problem, so I did a clean Frugalware install on a separate partition as well, and there bash segfaulted in konsole as well sometimes. This ringed a bell, memtest!</p><p>After about 15 mins, memtest found numerous errors, then I rode back to the shop where I bought it and I asked for an other module. The interesting points were:</p><p><ul>
  <li>Actually the good ram was cheaper than the bad one they gave me the first time.</li>
  <li>When I inserted the 2G module, the original 1G ram wasn't anymore used as the 0-1G range, but it shown up as 2G-3G.</li>
</ul></p><p>Now I hope next time I have to increase my ram amount, x86_64 will be mainstream so that I won't have to suck again with a 'custom' architecture. ;)</p>
++++
