= New firefox profile

:slug: new-firefox-profile
:category: hacking
:tags: en
:date: 2010-01-05T13:59:48Z
++++
<p>I'm continously upgrading my Frugalware installation, IIRC I installed 0.2 on this Clevo machine and I never saw any reason to reinstall. Sadly the situation is not that easy with applications, for example firefox's profile tends to grow from 20M over 100M and the only way to really get rid of all the junk it has is to start over.</p><p>Given that in the last month I did not really have time such minor problems, now I decided to solve this by doing an mv ~/.mozilla{m,.orig}.</p><p>I must note that I'm not a typical firefox user, given that I store my passwords in cpm, bookmarks on delicious (as I use multiple machines and I trust those applications/services more than firefox), and finally all the extensions I use are installed via Frugalware firefox-$extname packages.</p><p>Now I thought that this way the new profile usage will be easy enough, though there are still a few things to note:</p><p><ul>
  <li>The two <a href="http://delicious.com/help/bookmarklets">delicious bookmarklets</a> should be installed again.</li>
  <li>The <a href="/blog/enjoying-search-autosizer">searchbar autosizer</a> addon has bad defaults, I like to have the search bar with a fixed 203px size (355px on 1280x800)</li>
  <li>Finally I forgot I have a custom userChrome.css:</p><p><pre>
.tabs-newtab-button { display: none; } /* remove New Tab button */
</pre>
</li>
<li>
Change browser.backspace_action to 0 to make backspace to a back (as on Windows).
</li>
</ul></p><p>Other than that, no changes were necessary.</p>
++++
