= pptp client howto on linux on console

:slug: pptp-client-howto-on-linux-on-console
:category: hacking
:tags: en
:date: 2010-02-09T17:39:00Z
++++
<p>So I saw a few howtos on how to set up ms pptp client on linux, but they're mostly about how to click on networkmanager or other guis, so basically they hide the real detail, IOW what config files are actually used.</p><p>First install the necessary packages:</p><p><code>
# pacman-g2 -S ppp pptp
</code></p><p>Here is what I have under /etc/ppp:</p><p><code>
# cat chap-secrets
# Secrets for authentication using CHAP
# client        server  secret                  IP addresses
$user           PPTP    $secret                 *
</code></p><p><code>
# cat options
lock
</code></p><p><code>
# cat options.pptp
lock
noauth
nobsdcomp
nodeflate
</code></p><p><code>
# cat peers/$network
pty "/usr/sbin/pptp $server --nolaunchpppd"
name "$user"
file /etc/ppp/options.pptp
remotename PPTP
require-mppe-128
refuse-eap
ipparam $network
</code></p><p>And to bring up ppp0:</p><p><code>
# pon $network debug dump logfd 2 nodetach
</code></p><p>If it works fine, you can just use:</p><p><code>
# pon $network
</code></p><p>(Obviously replace $user, $secret, $server and $network with real values.)</p><p>One thing I did not figure out is how to configure it to set the default gateway as well. Right now I use the debug mode, then in the output I see the remote address, finally:</p><p><code>
# route add default gw $remoteaddr
</code></p><p>Other than that, it works fine - without any damn gui! :)</p>
++++
