= Praga

:slug: praga
:category: misc
:tags: hu
:date: 2010-08-19T00:56:32Z

image::https://lh3.googleusercontent.com/wwGxdc7zoEvqRSAR6B-cI4f-Y8dJrOJRhzvF73rcelV006CGFYtbvHVWJ9DjPG68dHRTrl3LRKdjjzHFZj-dEQCgDhSJwUufaAck_JRp2Y7fLVHRodpnZRRQwVrb6uiSsixPJL01dQ=w640[align="center"]

A multheten par napot toltottunk Pragaban, az ut soran felgyulemlett online tartalmakat igyekszem most egy csokorba gyujteni:

- link:/file/praga/mgmapscache-praga.tar.xz[mgmaps tarball] mivel az utikonyvben levo terkepen tul
  sok volt a "majus elseje hid" es hasonlo elnevezes

- link:/file/praga/mirror-maze.mp3[a mirror maze (ld kepek lenn) introja], ezt minden telefonra
  elkuldtek aki az objektum kozelebe ment es be volt kapcsolva a bluetooth+lathatosag a telefonjan

- link:/file/praga/praguetowers.jar[cseh/angol/nemet tajekoztato midlet], ezt u.ugy broadcastoltak
  mint az elozo introt

Mielott vegeztunk volna a valogatassal/feliratozassal, masok megtettek gyorsabban, de vegul ma vegre
sikerult idot szakitani a https://www.flickr.com/photos/vmiklos/albums/72157670562819412[sajat
kepeink] publikalasara is.

Elso korben ennyi, reszletesebb beszamolora most nem vallalkoznek, a kepekbol lathato, hogy az ido
nagy reszet varosnezessel toltottuk. :)

Frissites: meg par info amit mar nem akarok a TODO-mban tartani, ugyhogy ide irok:

- A Budapestrol befuto vonat a "Hlavni Nadrazi" nevu palyaudvarra erkezik.

- A szallasunk (a bences "http://www.brevnov.cz/[rendhaz]) mellett levo hotelt Szent Adalbert
  hotelnak hivjak, postacime Markétská 28/1 Praha.
