= samba, gentoo

:slug: samba-gentoo
:category: hacking
:tags: en
:date: 2010-03-06T15:36:55Z
++++
<p>Sorry, I'm continuing the story of uninteresting challenges I had in the last two days. Or if they look like interesting ones, please continue. ;)</p><p>Two days ago we (at work) had to repair a samba installation after a 3.0.x -> 3.2.x upgrade. There were 3 problems:</p><p><ul>
  <li>the firewall config had to be updated, to allow incoming tcp connections on port 445</li>
  <li>somehow smbd was listening on ipv6 only, just listing all network interfaces in the config was enough to make it listen on ipv4 as well</li>
  <li>for another strange reason it no longer accepted hostnames on its whitelist, using ip addresses directly did the trick</li>
</ul></p><p>The other story from yesterday was fix up the firewall configuration at a small office. The problem was that till now they had a PPPoE connection and the firewall used NAT to share the internet access to the desktop machines, but now they switched to a radio-based access, they got a new modem which did not support PPPoE. Of course in short I just got the usual "the internet does not work!" bugreport. ;)</p><p>I must note that I'm not a sysadmin at this office, I just stepped in as the local sysadmin was a SPoF in the system and he (temporally?) disappeared and they asked me beause of "the hours is burning" effect. :)</p><p>So all I had to do is to alter the server configuration, which was running Gentoo. I never touched such a machine before, and it's configuration is (of course, since I'm used to our netconfig) weird, but at least the off-line documentation was enough. So after RTFM, I just had to turn off pppoe, set the dns and the default gateway to the address of the new router and all was fine. One notable interesting fact was that there was no damn vi on the server. Given that emerge takes a lot of time, I had to suck with mcedit. :P</p><p>Conclusion: yet another example why offline documentation is important, even in case nowadays "there is internet everywhere". ;)</p>
++++
