= Systemd: kernel, bluetooth, bitlbee

:slug: systemd-3
:category: frugalware
:tags: en
:date: 2010-12-27T20:34:11Z
- Finally I can run systemd on my desktop, and not in a virtual machine
  only, since there is
  http://thread.gmane.org/gmane.linux.kernel/1080727[a patch] for the
  sched/cgroup issue I had. It was not a systemd bug, but systemd
  triggered a kernel issue, which was hidden so far.
- I just
  http://frugalware.org/pipermail/frugalware-git/2010-December/055098.html[updated
  our bluez package], and bus activation works fine. This means bluetoothd
  is not started till somebody connects to it. Given that I sometimes do
  not log in to KDE to use kbluetooth, but just want to do something on
  the console, where having bluetoothd running is totally unnecessary, I
  consider this really nice.
- It came up on `#bitlbee` that there is a
  https://bugzilla.redhat.com/show_bug.cgi?id=662289[Fedora bug] where
  they ask for systemd unit files for BitlBee. So I
  http://bugs.bitlbee.org/bitlbee/ticket/738[created a patch], and the
  nice thing is that the second iteration now seems to be fine for
  Frugalware/Fedora/Debian, so we managed to build something cross-distro
  here. (I think I mentioned that's the #1 feature I like in systemd.)
