= Szent Laszlo kilato-kapolna

:slug: szent-laszlo-kilato-kapolna
:category: bringa
:tags: hu
:date: 2010-08-08T21:09:20Z

image::https://lh3.googleusercontent.com/eFJxG0QxzXD4lqRL1sPFVlQyhj3M6HW0HV6N1MUVZrHUTkDDpbhkWaCH5vThSd3LfnWZfJEuYLhIzmfVdg-uGle-HUSBvYCPixHM_QL5D1gnYEaIQQA57C-8wcpX7mMD0nAQ2CyxJA=w640[align="center"]

Szoval itt (http://www.kirandulastervezo.hu/Main.php?do=detailViewAction&id=301[bovebb info])
jartunk, de kicsit elobbrol kezdtem.

Az alapotlet az volt, hogy csinaljuk meg a /blog/godollo-30.html[k30-as] turat. Szokas szerint
Godollore is mar bringaval mentem ki, ott talalkoztam batyammal, aztan vele indultunk tovabb.
Mogyorod es Fot kozott figyeltunk fel a cimben szereplo epitmenyre. Sajnos a tegnapi eso miatt eleg
saros volt a kornyek + az ut teteje mar tul meredek volt a biciklizeshez, de szerencsere igy is max
50m-t kellett tolni a gepeket. Teljesen veletlenul osszetalalkoztunk ott egy parral akik elmeseltek,
hogy az epitmeny by default zarva van, a Mogyorodi onkormanyzaton lehet elkerni a kulcsat, amit ok
meg is tettek, igy felmehettunk. ;)

Aztan Foton a minimalis magammal hozott kajat megettuk, vizvetel kozben egy helyi bacsi
elmagyarazta, hogy azert a viz a legerosebb folyadek, mert az meg a hajokat is elbirja. (!)

Vegul Godollon a Friczy altal nepszerusitett vendeglatoipari egysegbe tertunk be, ahonnan mar csak a
szokasos hazagurulas volt hatra.

Netto ido 4h59m01s, brutto ido 7 ora, tav 110.64km, atlag 22.1km/h (kifele siettem, mert nem akartam
sokat kesni, igy meglepo modon Bptol Godolloig sikerult 24.9es atlagot produkalni), max 61.2km/h
(Gellerthegyrol lefele vasarnap reggel kifejezetten tagak a lehetosegek).
