= Szokasos evvegi osszefoglalo

:slug: szokasos-evvegi-osszefoglalo
:category: misc
:tags: hu
:date: 2010-01-08T13:12:16Z

Ahogy link:|filename|/2008/szokasos-evvegi-tizes-osszefoglalo.adoc[tavaly] (meg a korabbi evekben),
iden is adta magat, hogy csinaljak ilyen listat, hogy mi volt jo az elmult evben. A kulonbseg csak
annyi (azon kivul, hogy csak addig gyujtottem amig jolesett, nem 10-ig), hogy most nem volt idom ezt
szilveszterkor postolni, de jobb kesobb, mint soha.

Idobeli es fontossagbeli sorrenddel nem torodve:

- Februarban eletemben eloszor voltam Franciaorszagban, sielni
- Aprilisban ismerkedtem meg Vele ;)
- Tobb, mint 4 ev utan raszantam magam, hogy fogorvoshoz jarjak, szerencsere az itteni "kiosztott"
  is tokjo, szoval egy vasamba se kerult
- Nyaron voltunk egy hetet Romaban
- BME: meg tavaly evvegen levizsgaztam az utolso BSc-s targyambol, igy most januar elejen mehettem
  zarovizsgazni
- Szeptemberben vettem egy Kona Caldera bringat, azota se bantam meg. :)
- Nemsokkal utana volt a Margita kupa utolso bringas teljesitmenyturaja, aminek az eves
  teljesitmenyet kupaval jutalmaztak. ;)
- Iden nyaron (a GSoC tamogatasaval) a swig-en dolgoztam, igazi kihivas volt, es kifejezetten
  erdekes 2heti idotoltes.

Nem olyan nagy dolog mint a tobbi, de amugy novemberben volt az ominozus eset, hogy meguntam az
ujabb b2evo verziokhoz portolgatni a custom patcheimet, rajottem, hogy annyira nem is fontosak,
ugyhogy most "vanilla" b2evo fut.
