= OOXML / PDF Digital Signing in Draw and elsewhere conference talk

:slug: libocon2020
:category: libreoffice
:tags: en
:date: 2020-10-16T17:53:30+02:00

image::https://lh3.googleusercontent.com/4cDltVS1u4m8FWC9Bb54TWILfzrFEXKNUcKKE6cxTIzsDWbX4SXPNw6JM01eLVzyqSqsyWhukcXXWmlJthx9q8tdbqO1LfO8FQECzBcEK3ZQl1lCXdpoAFGKZn_H9sNy0QLgNpPox_w=w1920[align="center",link="https://files.speakerdeck.com/presentations/eae85c2ac9d443708bda7ca26b3f5a6f/pdf-visible-sign-loconf-online-2k20.pdf"]

Today I gave a https://events.opensuse.org/conferences/oSLO/program/proposals/3187/[OOXML / PDF
Digital Signing in Draw and elsewhere] talk at the LibreOffice Conference 2020. The (virtual) room
was well-crowded -- somehow people find digital signatures interesting. ;-)

It contains an overview of the ODF/OOXML/PDF signing feature set and also details the latest
improvements, like visible PDF signing.

I expect quite some other slides from other Collaborans and the wider community will be available on
http://planet.documentfoundation.org/[Planet], don't miss them.

You can get a snapshot / demo of Collabora Office and try the presented features out yourself right
now: https://www.collaboraoffice.com/collabora-office-latest-snapshot/[try unstable snapshot].
Collabora intends to continue supporting and contributing to LibreOffice, the code is merged so we
expect all of this work will be available in TDF's next release too (7.1).

// vim: ft=asciidoc
