= Apátistvánfalva

:slug: apatistvanfalva
:category: bringa
:tags: hu
:date: 2012-05-28T22:26:58Z
A múlt hetet http://www.apatistvanfalva.hu/[Apátistvánfalván] töltöttük. Végül
nem kocsival mentünk, így értelemszerűen inkább a közelebbi környéket jártuk
be:

- http://www.ketvolgy.hu/[Kétvölgy]: itt a Vendvidéki Vendégházban próbáltunk
  ebédhez jutni, felettébb furcsállták, hogy hétköznap meleg ételt keresünk, de
  végül kiváló krumplileveshez jutottunk.
- Szentgotthárdon a http://www.termalpark.hu/[Thermal Spa] egy nemrég felhúzott
  termálpark, nem meglepő módon a sok osztrák között inkább a magyar érzi magát
  külföldinek... de amúgy ötletesen van megoldva, például a kabinhoz használt
  tokennel lehet kaját rendelni az épületen belül, és csak a végén kell fizetni,
  kikerülve ezzel a védetlenül hagyott pénztárcák problémáját.
- http://www.orfalu.hu/[Orfalu]: Na itt a haranglábon kívül nem találtunk
  semmit, cserébe utána ellátogattunk a
  http://www.harsasto.extra.hu/[Hársas-tóhoz], amit nem bántunk meg, később még
  egyszer visszatértünk ide biciklivel.
- http://www.oriszentpeter.hu/[Őriszentpéterre] bringával mentünk, de végül a
  nap inkább amiatt lett emlékezetes, hogy visszafele megálltunk Pityerszeren
  megnézni a skanzent, illetve megkóstoltuk, mi az a
  http://hu.wikipedia.org/wiki/D%C3%B6d%C3%B6lle[dödölle].
- Utolsó teljes napunkon elmentünk http://farkasfa.net3.hu/[Farkasfára]
  turistaúton, de sajnos itt (pedig ez már hétvégének számított) semmilyen
  ebédelési lehetőséget nem találtunk, így gyorsan visszatértünk a szállásra.

Szállásadónk az http://apathotel.hu/hu/[Apát Hotel] volt (csütörtökig mi
voltunk az egyetlen vendégek), a turistautakon való navigációhoz meg a
https://play.google.com/store/apps/details?id=menion.android.locus[Locus] volt
segítségünkre.
