= Samsung Galaxy S

:slug: galaxy-s
:category: en
:date: 2011-12-22T21:08:00Z

As link:|filename|/2011/s40-apps-i-use.adoc[this post] already suggested, about a week ago I
replaced link:|filename|/2007/3110c.adoc[my S40] with $title. (Yes, I know that S II is
just released, but that pushed down the price of S a bit, and I don't want to
waste so much money for a phone.)

So far I'm quite pleased about the product, here are the tools I used to
migrate data:

- gammu, to convert the calendar to ics, which can be imported by the calendar
- https://github.com/vmiklos/vmexam/blob/master/gammu/gammu2gcontacts[gammu2gcontacts] to extract
  contacts from the gammu backup (link:|filename|/2011/gammu2gcontacts.adoc[earlier post])
- http://www.mgmaps.com/[mgmaps] can export to kml, which can be imported to my maps
- finally a throw-away (use once, and never look back) script to generate emails from my notes, which can be imported by https://market.android.com/details?id=org.dayup.gnotes[gnotes]

The hardware is supported by http://www.cyanogenmod.com/[CyanogenMod], but I did not experiment with that so far. (http://forum.xda-developers.com/showthread.php?t=723596[bookmark])
