= Web framework fejlesztes

:slug: web-framework-fejlesztes
:category: munka
:tags: hu
:date: 2011-04-08T00:28:01Z
Ilyesmivel kerestek meg, en most nem keresek munkat, de hatha mas igen.

[quote]
____
Olyan embert keresek aki nagyon ért valamilyen web frameworkhöz.
Akármelyik javascriptes vagy GWT vagy javas vagy esetleg groovy on grails.

A feladat egy már meglévő web alkalmazás felületének az átalakítása lenne.
Spring Roo-val készítettem de már nem használom mert túl sok mindent átírtam
benne és a Roo korai verziója ezt nem támogatta megfelelően, az upgrade meg
még keményebb lett volna.
Ebből adódóan Spring MVC-t használok sima JSP-vel. (Akkori Roo-ba még nem
volt GWT)
Van pár ajax hívás, pl. autocomplete mezők, de nem ez a jellemző, ehhez
jQueryt használtam és nehány egyéb dologhoz még Dojo-t mert a Roo alapból
azt használja de nekem nem jött be.

Szeretném sokkal felhasználóbarátabbá tenni az egészet és ehhez a JSP meg az
én javascript tudásom nagyon kevés.
A teljes megjelenítést szívesen lecserélném bármi másra ennek érdekében.
Konkrétumokat akkor mondanék ha van jelentkező, nem azért mert titkos csak
nekem is össze kéne szedni :)

Nem fulltime munkáról van szó és nem nagy pénzről, de legalább valami
sajátot lehet csinálni.
Én heti 10-15 órában foglalkozom ezzel, persze a megrendelő szeretné ha
többet csinálnám, de valamiből meg is kell élni és munka+gyerek mellett
ennyi jut :)

Kb 25 CRUD karbantartó van, ebből 4-5 bonyolultabb.
És kb 5 statisztika képernyő amiken csak egy táblázat található. Meg egy
grafikonos. De ezek fognak bővülni a közeljöbőben.
____

Jelentkezes, tobb info: leventewe kukac gmail.com.
