= az ur hangja

:slug: az-ur-hangja
:category: konyv
:tags: hu
:date: 2008-06-11T23:25:46Z
++++
<p>a nemreg kiadott "lem osszes" elso koteteben ez az utolso regeny. elegge mas stulisa van mint a korabbaiaknak, es talan nem is rossz, h nem ezt tettek a kotet elejere, de ettolmeg vannak benne nagyon jo reszek.</p><p>egy kis kedvcsinalo:</p><p>Valahol meg kell vonni a szolidaritás határát. A Földön soha senki sem helyezte alacsonyabbra annál az elágazásnál, ahol a növények elválnak az állatoktól. Az instrumentális gyakorlatban nem lehet egyébként a szolidaritás tárgyainak tekinteni például a rovarokat. Ha tudnánk, hogy a csillagokból küldött jelzés valamilyen okból feltétlenül megköveteli a földi hangyák pusztulását, bizonyára úgy ítélnénk, hogy ``érdemes" feláldozni a hangyákat. No igen, de mi, a magunk fejl?dési fokán, szintén hangyák lehetünk valakinek. Ama lények szempontjából a szolidaritás nem terjed ki feltétlenül az olyan am?bákra, mint mi vagyunk. Talán ésszer? indokaik is vannak. Hátha tudják, hogy a galaktikus statisztika szerint a földi pszichozoikum-típus eleve ki van szolgáltatva a technikai fejl?dés szeszélyeinek, tehát létünk egyéb irányú veszélyeztetése nem olyan borzasztó, hiszen ``valószín?leg úgysem lesz bel?lünk semmi".</p><p>ilyesmi :)</p>
++++
