= Enjoying search autosizer

:slug: enjoying-search-autosizer
:category: hacking
:tags: en
:date: 2008-12-09T14:34:15Z
++++
<p>This was getting more and more annoying. So my problem was that whenever I searched for something in Firefox, I typed it to the search bar and the query was left visible there. This is just totally idiotic for (at least) two reasons.</p><p>First, those search queries show what you are thinking about. It's normal that you don't always speak about what you are thinking about, so why would it be logical to <em>always</em> show what are you searching for. This is just uncomfortable for other people, they come to your box (somebody from the family, etc), want to search for something and they see what you were searching for, and they will think about "why did he search for this" - not that they care about it, they just don't want to see this info.</p><p>Second, I regularly work in a library and such places where the contents of a query may be just sensitive info and/or NSFW.</p><p>OK, so as the result of the previous problems, I saw myself just hitting enter in the search box to get the normal search form and search there so the original search box remained empty. This was abnormal.</p><p>Today I spent some time searching for a proper solution for this and sort-of found it: the <a href="https://addons.mozilla.org/en-US/firefox/addon/1172">Searchbar Autosizer</a> extension. Actually it's stupid as it re-sizes your search box (so make sure you remember the size of it <strong>before</strong> you install this extension), but you can make it a fixed value again and in the second dialog of the preference wizard you have the option to clear the search box right after you hit enter. Excellent, that's what I was looking for. :)</p>
++++
