= Frugalware darcs repo in the darcs "big-zoo"

:slug: frugalware-darcs-repo-in-the-darcs-big-z
:category: hacking
:tags: en
:date: 2008-12-24T03:35:23Z
++++
<p>"big-zoo" is a collection of darcs repos, the darcs developers do benchmarks using this collection from release to release.</p><p>Recently our old Frugalware repo <a href="http://code.haskell.org/darcs/big-zoo/">has been added</a>, which is good, for multiple reasons.</p><p>First, now I can say that the reference for a good darcs exporter is the big-zoo, our old repo contains weird patches which were not yet part of "big-zoo" so far. Not that I'm evil, but I want to show that currently darcs-fast-export is the only exporter that can correctly convert all the repos in "big-zoo".</p><p>Second, it is a huge repo, so developers can how see the corner cases where darcs is really slow for a huge repo - though the GHC one was already included which is almost as big as our one and the most annoying cases are already optimized recently. (No, of course I can't compare it to git, I compare it to darcs-1.x.)</p>
++++
