= fun on the gsoc list

:slug: fun-on-the-gsoc-list
:category: gsoc2008
:tags: en, hacking
:date: 2008-07-21T23:07:16Z
++++
<p>The GSoC student list is not public, and to be honest, usually it's boring. In most cases you just want to read the mails matching ^From:.*google.com, and just delete the remaining junk. However, there was a funny thread there, about how others deal with the usual problem: if you want to describe others (read: who is not a geek) what do you do (hack PaX, rewrite git-merge, etc.) you probably need a half an hour. Or maybe it's better not describing your job at all. Let's see some funny quotes:</p><p>The "I gave up" one:</p><p><blockquote>After the first 10 fails, I decided to say the following as fast as I can:
Me: "I am doing "something" and Google is paying me to do it. I don't know why they are, but I assume its' because they aren't evil and stuff. End of story".
Other: Oh.
(Coding resumes)</blockquote></p><p>BTW, the guy adds vim support to anjuta. :)</p><p>If you have nice friends, you'll get:</p><p><blockquote>People who don't understand usually state as much, followed by, "...but if Google is paying you, that's pretty neat."</blockquote></p><p>The "involved" one:</p><p><blockquote>Unfortunately, I end up rambling for twenty-plus minutes and they are sorry they ever asked...</blockquote></p><p>The "practical" one:</p><p><blockquote>In my case, everyone in my university thinks it is an intern program so they ask me when I am going to travel. I have memorized the response.</blockquote></p><p>The "religious":</p><p><blockquote>I spent about twenty minutes explaining to a reporter from business week the finer points of open source vs free software.</blockquote></p><p>And the typo kign:</p><p><blockquote>> thanks very much gays ......
>
GUYS .... really, I was  miss typed ...
now, again. Thanks very much  GUYS</blockquote></p><p>(I hope this post does not count as a leak, though. :P)</p>
++++
