= istvan a kiraly

:slug: istvan-a-kiraly
:category: zene
:tags: hu
:date: 2008-08-02T00:56:59Z
++++
<p>noszoval, bmerol hivtak erre a dologra. kicsit gagyin indult a dolog, mert kiderult, hogy nem arrol van szo h xynak van ingyenjegye csak 1xuen mivel szabadteri a koncert ezert nyilvan a keritesen kivul is tokjol hallhato :P</p><p>de ettol fuggetlenul nem volt rossz. kicsit megteveszto a cim, mert itt nem egy komplett eloadasrol van szo (vegulis az annyira nem is erdekelt volna, lattam mar van 6 eve), hanem egyreszt az elso "felvonasban" a rockopera szereploi adtak elo mindenfele regebbi dalt, koncz zsuzsatol kezdve nagy fero 8 ora munkajaig mindene okossagot, a masodik reszben pedig magabol a rockoperabol voltak reszletek.</p><p>a masodik resz a rockopera elejenel kezdodott, de aztan hagytak ki reszeket. vegul nem vartuk meg a veget, mert a tarsasag egy resze parazott, hogy meg a blahan el akarja erni az utolso metrot, de amennyit hallottunk a dologbol az nem volt rossz. penzt (a hamburgerre kiadott penzt leszamitva) mondjuk nem biztos h adtam volna erte ;)</p>
++++
