= nights in rodanthe

:slug: nights-in-rodanthe
:category: film
:tags: hu
:date: 2008-11-25T15:47:49Z

image::https://lh3.googleusercontent.com/Ry2yh2KYojwbE7HFJ7Zg-4ssfw9tUTVUxrt93LFp4U6lnrRnN7jGfHzQW8hhh8a30dS27WuFOZouK2fNXTJQ7VmUZ7vIjwRtIXI36BniWzJ7QLEheFJ976GImR2NjfPaNkrmg4TB7g=w640[align="center"]

tekintsunk el attol, hogy a cimbol alkotott mozaikszo eppen egy nor kapu ;)

amolyan atlagos romantikus drama, elolvastam elotte egy ajanlot, nem tobb es nem kevesebb annal amit
vartam. tekintve, hogy nem talaltam angol feliratot, ra voltam kenyszeritve, hogy gyakoroljam vegre
egy kicsit a felirat nelkuli angol filmnezest. (valszeg nem jogos, de ettol fuggetlenul azert mindig
sikerelmeny, mikor a film vegen feltunik, hogy "je, ez nem volt szinkronos" ;) ).

visszaterve a mozikban mar egy honapja jatszott filmre, a ket foszereplo Diane Lane (untraceable) es
Richard Gere (na ovele meg nem talalkoztam). a tobbi szereplo gyakorlatilag elhanyagolhato, bar a
harrypotter-arcu Charlie Tahan (i am legend) itt nemigazan artatlan kisgyerket jatszik, inkabb az
igazi 12eves geek megtesitoje. :)

(http://www.imdb.com/title/tt0956038/[imdb], http://www.youtube.com/watch?v=wABFdUIIxlw[trailer])
