= nosleep

:slug: nosleep
:category: misc
:tags: hu
:date: 2008-08-06T00:24:20Z
++++
<p>szoval ahogy a linkben is olvashato, resztvettem a "SummerNosleep 2008" versenyen. roviden annyibol all a dolog, hogy minel tovabb ki kell birni alvas nelkul. annak bizonyitasara pedig hogy ebren vagy vezetned kell egy blogot amibe postolsz orankent. szal pont ugy ahogy a twitteren lehet csinalni.</p><p>korabbi dolog amire emlekszem, hogy egyszer meg ovkban (cserkesz orsvezeto-kepzo tabor) volt ilyen, h egyszer 2 orat aludtunk aztan utana meg semmit. szal szeretem az ilyen temaju kihivasokat, kivancsi voltam meddig birom.</p><p>az elso 48 ora aranylag siman ment, bar mind2 ejszaka volt kb egy 4oras intervallum amikor nagyon elalmosodtam, es tenyleg ugy ereztem utana, mintha valami csoda tortent, hogy nem aludtam el ;)</p><p>igazabol a 48. oram korul kiesett a 22 emberbol a maradek 2 konkurencia is, de akkor meg ugy gondoltam birom tovabb, igy megkisereltem nemcsak megnyerni a mostani versenyt, de a korabbi versenyek idaigi rekordjat is megdonteni.</p><p>az utolso nap mar nehezebb volt, eleg faradt voltam, nehezen tudtam barmi ertelmeset csinalni. vegul az utolso ora volt a legszornyubb. valami lehet ebben a 68 oraban, mert ha valaki azt keri h csinaljak 69-et, hat nem tudom hogy birom ki. igy aztan vegul csak par perccel dontottem meg a korabbi rekordot, dehat a lenyeg h megdontottem ;)</p><p>ami meg erdekes volt, hogy szemelyesen csak 2 usert ismertem a versenyzok kozul, ennek ellenere a csatin nagyon jo hangulat volt. mikor pedig mar kiestek az emberek, mindenki egyutt szurkolt hogy meg tudjam nyerni a versenyt. ez nagyon meglepett ;) a userek nagyresze kb 2 napja latott eloszor, megis folyamatosan batoritott, hogy meg tartsak ki, stb. :)</p><p>ugyhogy koszonet a szervezoknek a programert, es a tobbieknek a jo tarsasagert!</p>
++++
