= Persistent channel names in BitlBee

:slug: persistent-channel-names-in-bitlbee
:category: hacking
:tags: en
:date: 2008-12-22T02:35:51Z
++++
<p>See <a href="http://bugs.bitlbee.org/bitlbee/ticket/469">this ticket</a>. The idea is not to use "chat_randomnumber" as channel name, so that irssi can remember the layout.</p><p>We'll see how wilmer will welcome the idea. ;-)</p><p>OTOH, I still hate bzr:</p><p><pre>
$ bzr pull
Using saved location: http://code.bitlbee.org/bitlbee/
Format &lt;RepositoryFormatKnit1&gt; for http://code.bitlbee.org/.bzr/ is deprecated - please use 'bzr upgrade' to get better performance
No revisions to pull.
$ bzr upgrade
bzr: ERROR: The branch format Bazaar-NG meta directory, format 1 is already at the most recent format.
</pre></p><p>I guess it refers to the server repo, but PLEASE, why should I care about it? It's not my repo!</p><p>And again something else. I just started using tuxguitar. I like it, but having sound in it was not trivial. It turns out that the working setup is to run
<pre>
timidity -iA -Os
</pre>
and then disable the oss output plugin, enable alsa, and choose the timidity midi output in the sounds settings in tuxguitar.</p>
++++
