= practical common lisp

:slug: practical-common-lisp
:category: geek
:tags: hu
:date: 2008-05-11T12:21:24Z
++++
<p>[video:google:448441135356213813]</p><p>haat, egy atlagos tech talkhoz kepest ez eleg ratyira sikeredett. kezdve ott, hogy az egesz helyseg ugy nez ki mintha valami regen nemhasznalt pokhalos pincebe lennenek. az mar inkabb erdekes, hogy a csavo eleg nehezen erthetoen beszel szal nagyon oda kellett figyeljek, hogy ertsem mit mond. tartalom szempontjabol meg nagyreszt arrol szol, hogy javaban meg lehet csinalni 9999 modon a <a href="http://en.wikipedia.org/wiki/Visitor_pattern">visitor patternt</a>, de mindegyik rosszabb, mint ahogy lispben lehet. arra nem igazan sikerult rajonni, hogy akkor most a tisztelt hallgatosagnak le kene-e vonni ebbol egy olyan kovetkeztetest, hogy "tehat a lisp jobb" vagy wtf.</p><p>ja es megy folyamatosan az ajnarozas, hogy igazabol amirol o most itt beszel arrol o irt egy konyvet amit tessek megvenni, mert igazabol csak abbol lehet barmit is megerteni. kiraly.</p>
++++
