= Teljesitmenytura

:slug: teljesitmenytura
:category: bringa
:tags: hu
:date: 2008-10-13T21:07:48Z

image::https://lh3.googleusercontent.com/kpscW8g1qC3_qU9x3bbzM4_jCp1fZ3r2d0wniRAWqwnlacOh2uVOC6O8FNJy1_081gfDLBEd-VqpF3Qdt7W2YDr_FGJadWt4h8wzZZuO-hEtRdH8EpDLyHAz2TgsogCthb23QLo4ew=w640[align="center"]

minden evben ketszer szokott lenni ilyen cserkeszek altal szervezett teljesitmenytura, aminek a
bringas reszlege ugy nez ki, hogy marc15 kornyeken 48/96kmes tav van, okt23 kornyeken meg 56/112.
ertelemszeruen most mi ez utobbira mentunk.

keles 6korul, arpadhidnal talalkoztunk 7kor, majd ki budakalaszra, ott start. lett volna valami
reszveteli dij, de azt elfelejtettek elkerni. turautvonalat adtak, terkepet nem. es mi se vittunk.
pedig kellett volna, dehat utolag mar konnyu okosnak lenni.

reggel ilyen kotszitalos dolog volt, eleg fos mert alig lehetett kilatni a szemuvegbol meg a
puloverem is tiszta viz lett de aztan elmult, felszallt a kod, kisutott a nap, life is good. ja es
meg start elott tankolas peksegnel.

maga az utvonal eleg para volt mert kb ilyen 10km/hval kozlekedheto emelkedokbol (kitaposva lehetett
volna gyorsabb is de az hosszutavon nem megy) es ennek mondjuk negyszeresevel lefele-lejtokbol allt.
tehat kb teljesen ellentete egy balatoni karikazasnak, de talan nem is baj, igy volt benne ujdonsag.

a pecsetelopontokat eleg jol megtalaltuk, kiveve az utolsot. vegul (mint utobb kiderult) az urak
asztalanal - ami a gyakorlatban egy elhagyatott katonai objektum - visszafordultunk szentendre fele,
ott meg betoltunk egy pizzat aztan haza.

illetve nem haza, mert meg hivatalos voltam lagziba, szoval effektive ilyen fel2 korul ertem haza,
de anelkul azert ilyen este 8-9 lett volna csak.

eredetileg az motivalt h na akkor most letekerunk 100+kmt, es ez vegulis megvalosult, szal attol
fuggetlenul, hogy nem csinaltuk vegig sztem tokjo program volt, legkozelebb erdemes lenne terkeppel
megnezni ;)

vmikor a lagziban a zsebemben 0zodott a kmora, szoval pontos adataim nincsenek, de kb: tav 148km,
netto tekeres 8h, brutto 13h, max 55km/h, atlag 18km/h korul.

ja es az urak asztala elott/utan megalltunk szedrezni, ott keszitette LGee a post teteljen levo
kepet, meg a tobbit is (marmint a turan).
