= the edge of love

:slug: the-edge-of-love
:category: film
:tags: hu
:date: 2008-11-04T03:38:44Z

image::https://lh3.googleusercontent.com/lcnUbzqR2Z-KPhH2k9MotZI7QWF0HnsiJ8viuXsgZ68Pzrhgtf5b9WSpNJ2mT2POBRlWD9RKYrXpC1TerfnNYjVM4di7-iyK9cmUQkBrCuGVgrsqbjzs3rZ1hUPgC-KMzIgUYf45jw=w640[align="center"]

huh, regen lattam filmet premier elott, de ez erdekesnek igerkezett, es nem is bantam meg. erdemes
angol felirattal nezni, mert a Dylan versek megis masok eredetiben. sokban hasonlit a "vagy es
vezeklesre" (amiben szinten keira knightley jatszik) a korulmenyeket tekintve, viszont az egesz
cserekmeny itt tok jol meg volt csinalva. valamilyen szintu happy end is megvolt a vegen, de persze
nem tulzasbaveve, elvegre megiscsak egy dramarol van szo.

a masik noi foszereplo sienna miller, vele is lehetett talalkozni az alfie-ban, a casanovaban, es
erdekessegkeppen a "kis vuk" angol hangjat o adta. ferfi foszerepben cillian nurphy (dark knight) es
matthew rhys (sorted). szoval csupa ismeros arc.. csak ajanlani tudom. holnaputantol a mozikban! :)

(http://www.imdb.com/title/tt0819714/[imdb], http://www.youtube.com/watch?v=R2XN5elRKcI[trailer])
