= untraceable

:slug: untraceable
:category: film
:tags: hu
:date: 2008-05-30T15:24:24Z
++++
<p>[video:youtube:OLYo5tMylQM]</p><p>amolyan "nezzunk valami ujat" cimszoval, tegnap volt a premierje.</p><p>eloszoris egyszernezos film, leginkabb azert mert ha lelovik a poent a vegen akkor sztem mar nem erdekes. ezenkivul az elejen elkezdenek belemenni technikai reszletekbe, mint pl "meghekkeltek a szervert botnettel" amit jobb lett volna kihagyni, igy kicsit nevetseges lett az egesz. de aztan sikerul ezt helyrehozni, visszazokken a nezo a film milliojebe, elfelejti h ez csak egy gagyi jatekfilm. mellesleg pedig maga az alapotlet meg technikailag is korrekt. (alacsony ttllel - pl dyndns - elvileg tenyleg lehetne ilyen nehezen lekovetheto oldalt csinalni; ha meg kicsit bonyolultabb technikak is megengedettek akkor ott a tor, az mar mukodik es gyakorlatilag anonim.)</p><p>aztan jonnek durvabb jelenetek, neztem is h miert csak 16+os, ha van felperc szex egy filmben akkor az mar 18+, de ha vegig mutatjak ahogy a kensav lemarja valaki kezerol a hust az csak 16+, wtf?</p><p>de meg mindig az ilyen uncsi horrornal tartunk. ami miatt tetszett a film az az, h teljesen meglepo modon van mondanivaloja. az tiszta ugy, hogy a gyilkos egy orult, de ettol fuggetlenul van nehany erdemes es elgondolkodtato mondata.</p><p>akinek van hozza gyomra annak tessek megnezni.</p>
++++
