= vagy es vezekles

:slug: vagy_es_vezekles
:category: film
:tags: hu
:date: 2008-01-19T15:46:58Z
++++
<p>[video:youtube:zW_PfE56Cuk]</p><p>erdekes film. alapvetoen egy drama: egy 13eves kislany elszurja a novere es a pasijanak kapcsolatat, es elete vegeig bunhodik erte. vagy valami ilyesmi. tehat alapbol semmi olyan ami felkeltene az erdeklodesemet. nem olvastam a konyvet, tehat igazabol nemtom, h mitol lehet sikerregeny egy olyan konyv aminek a fo temaja a csaj onmarcangolasa.</p><p>miutan jol lehordtam, nezzuk a jo oldalat. egyreszt a zene sztem nagyon talalo, vannak benne korrektul kidolgozott jelenetek, es a szineszi teljesitmeny sem elhanyagolhato.</p><p>a film foszereploje nyilvan a hug, de azzal, hogy betoltak a novernek keira knightleyt a hangsuly nyilvan eltolodott. olvastam olyan kritikat ami szerint az egysegsugaru user azthiszi hogy mostmar ez csak egy romantikus vigjatek ahol valami erthetetlen modon gyertyatartokent megjelenik egy hug is, de azert ez sztem eros tulzas. az meg extra lol, hogy tenyleg kepesek voltak a filmben levo egyetlen szexjelenetet <a href="http://www.youtube.com/watch?v=SX1_sIb2M-w">kirakni</a> kulon a youtube-ra :D</p><p>szoval elsore aztmondanam, hogy szar film, igy nehany nap tavolsagbol aztmondom, hogy erdemes 1x megnezni.</p>
++++
