= atallas openblogrol

:slug: atallas_openblogrol
:category: geek
:tags: hu
:date: 2007-11-02T14:33:41Z
++++
<p>nos tehat. nezzuk. azt igertem a minap h megosztom hogyan is alltam at b2evo-ra openblogrol. a trukk a kovetkezo. az openblognak van egy xml api-ja, azon keresztul kimentjuk az bejegyzeseinket mt (movable type) formatumba. ezutan ezt barmelyik mainstream (b2evo, wp, stb) blog engine be tudja mar importalni. maga a konverter script <a href="/file/convert.py">itt</a>. hasznalat az valami ilyesmi:</p><p><code>$ python convert.py usernev out.txt</code></p><p>(az addict userek szerkeszthetik a script elejen levo kategorizalot, meg lehet adni, hogy ha foo szerepel a postban akkor bar legyen a kategoria ertelemszeruen)</p><p>ezutan pedig mar csak az out.txt-t kell megetetni uj kedvencunkkel.</p><p>ja meg1. a b2evoban a kommentekben a hivatkozasok (ugy tunik) fixen le vannak tiltva importkor, pedig nyilvan mi nem a html kodot szeretnenk latni. lusta voltam pontosan kikeresni h mit es hol kell atirni, tehat a leg1xubb az volt h futtatom <a href="/file/fixcomments.py">ezt</a> a scriptet (at kell benne irni a user/pass/dbname valtozokat) es igy maris szep az elet</p>
++++
