= elso

:slug: elso
:category: geek
:tags: hu
:date: 2007-10-31T19:26:28Z
amugy link:/blog/ez_az_elsp_blog_bejegyzes.html[nem]. a b2evo szerint ez lesz
a 828. bejegyzes. de ezen a cimen az elso.  tehat megis.

nos, nezzuk mi ez itt. az openblog.hu sajnalatos modon megszunt, nem az en
nevemen volt a domain, akinek meg volt az egyszeruen nem fizette be a penzt h
meghosszabbitsak, aztan nyilvan lecsaptak ra, leven jo kis nev.

akkor jott az otlet, h kene valami uj nev. hamar valtok, akkor kicsit
ujragondoltam az egeszet, es sajnalatos modon arra jutottam, hogy igazabol az
openblog arra kellett, mert kivancsi voltam, hogy az akkori tudasommal tudok-e
irni egy blog engine-t, olyat amit masok is fognak hasznalni. es tokjo volt
latni, hogy igen. persze akkor meg nem gondoltam arra, hogy azt majd karban is
kell tartani, leven hosszutavon az egesznek az a lenyege hogy a portal mogott
van valami orult arc aki folyamatosan dolgozik uj feature-okon. ami
nyilvanvaloan hianyzott az openblog.hu esteben.

a blogs.frugalware.org-on mar hasznaltuk egy ideje a b2evo-t, igy aztan
regeltem sajat domaint es frissitettem hozza a magyaritasat. tehat egyben ha
talaltok valami magyartalan dolgot az oldalon akkor azert nyugodtan tessek
szolni, aztan megprobalom javitani.

persze volt az openblogon masoknak is blogja, tehat nem akarom eltitkolni,
hogy hogy exportaltam az ottani bejegyzeseket, de ezt most tuti nem irom le,
majd mondjuk holnap

// vim: ft=asciidoc
