= szabo magda - abigel...a divatot

:slug: szabo_magda_abigel_a_divatot
:category: konyv
:tags: hu
:date: 2007-02-12T19:55:32Z
++++
<a href="http://www.libri.hu/hu/book/regenyek/magyar_szerzok_muvei/kortars_szepirodalom/abigel" target="_self">szabo magda - abigel</a><br><br>...a divatot elenk figelemmel kiseri, meglatszik remek fules sapkajan, valasztekos izlessel vasarolt nyakkendoin. szellemenek szipokazo elessege egyenesen kozcsodalat targya, melyet igazan csak hosi lelkulete, marcona ferfiassaga es mar-mar legendas batorsaga mul felul. a vert oly kivaloan birja, h az hirlik, atkepzik sebeszorvosnak. mihelyt megkapja uj diplomajat, siet megkerni szive valasztottjat, aki egy szavara igent mond, hiszen ki tudna ellenallni ennek a dalianak, akire barki nyugodtan rabizhatja az eletet, kiveve ha jon a vonat es megerett az alma.<br><br>Tormanak is konyv volt az ajandeka, lebilicseloen erdekes olvasmany, nyilvan a nagybatyja valasztotta: "A diakonisszaintezmeny tortenete", abban is benne voltak az autogramok.<br><br>...o ebren fekudt meg sokaig, es azon tunodott, milyen furcsan es varatlanul kovetkeznek be az ember eleteben a legjelentosebb esemenyek. Nem ugy, nem is akkor, ahogy es amikor varja az ember, maskeppen, mas elozmeny utan, valahogy logikatlanul. Egyszer csak ott van valaki a karzaton, az ember ranez, az meg vissza ra, es attol megvaltozik az elet egeszen.<br><br>tegnap fejeztem be, nekem tetszett. hosszas elemzes helyett talan ertelmesebb kedvcsinalonak emliteni a fenti 3 idezetet :)<br>
++++
