= telefon 2oo7ben

:slug: telefon_2oo7ben
:category: geek
:tags: hu
:date: 2007-11-09T01:25:41Z
++++
<p>a jelenlegi telefonom egy jo oreg nokia 3510i-s darab. meglepo, de 4 ev hasznalat utan is nagyjabol meg vagyok vele elegedve. roviden, amit szeretek benne:
<ul>
  <li>az aksi meg mindig 1hetet bir (eredetileg majdnem 2hetet birt)</li>
  <li>wapot tudja teljesen jol, igy pl tudok ircelni rola</li>
  <li>szines kijelzo</li>
  <li>ugyan kell egy kicsit szerencsetlenkedni a soros kabellel, de azert lehet szepen backupolni</li>
  <li>van rajta midp1es java, tehat ha nagyon kell akkor tudok ra irni sajat progikat</li>
</ul></p><p>nezzuk milyen bajok vannak vele. megjegyzem, hogy ezek gyak. mind kicsi gondok, semmi komoly bajom nincs</p><p><ul>
  <li>a billentyuzete meglehetosen amortizalodott, a felfele gombot pl kb csak en tudom megnyomni, ha masok nyomjak azt altalaban jobboldali funkciobill.-nek veszi :)</li>
  <li>mivel midp1es java van csak rajta, pl ssh-zni nem lehet rola, pedig neha hasznos lenne</li>
  <li>termeszetesen nincs rajta kamera, es 2oo7ben talan ez mar nem annyira draga mulatsag, 1-1 vicces dolgot lefenykepezni meg nem is rossz</li>
  <li>a soros adatkabellel szivas szenvedni, leven a notimon mar csak usb van</li>
  <li>eltelt 4 ev, gondolom a mai aksik azert mar valamivel tovabb birjak</li>
</ul></p><p>amolyan nokia fan vagyok, tehat ha vennek is vmi ujat, akkor az tuti tovabbra is nokia lenne, ebben biztos vagyok</p><p>annyi mar valoszinu, hogy az utolso opcioban a smartphone-ok elbuknak, leven azoknak meg a mostani telefonomnal is rosszabb az aksijuk. azthiszem az lesz, hogy ezzel a listahoz el fogok setalni a pannonhoz es kivancsi vagyok h mit mondanak ;)</p>
++++
