= zarora?

:slug: zarora
:category: misc
:tags: hu
:date: 2007-02-12T20:09:43Z
++++
zarora? vicces most errol irnom, leven ha jolszamolom a mai nap folyaman ez a 3. post. mind1. ugy kb szeptember ota szepen minden nap irogattam, aztan mostanaban ez igy neha elmaradt. nem ok nelkul. karinthy <a href="http://grin.hu/mindburp/karinthy_eloszo.html" target="_self">eloszavaban</a> van ez a "nem mondhatom el senkinek, elmondom hat mindenkinek". igen, kb errol szol ez az egesz blogolosdi. mikor azokat a napi kis poenokat, mokas sztorikat, barmit amit ide postolgattam nem igazan volt kinek elmondani, igy aztan ide irogattam, kozbe sportot uzve abbol, h minden napra jusson vmi, es persze fun volt, leven a blog latogatottsaga folyamatosan nott. de valami azert nincs egeszen rendben. mas emberek nem a netre postoljak, hanem elmondjak ezeket mas <i>embernek</i><br />ugytunik most ennek a postolgatos idoszaknak (mar ami a szemelyes elmenyeket erinti) kicsit vege. majd meglatjuk. pedig poen utolag visszanezni, de megse eri meg<br /><br />irhatnek arrol, h hogyan sikerult 1 helyett 4kor hazakeveredni penteken meg hasonlok, de mikor vegre hazaertem mar nem az volt az elso h hu errol most blogolni kell, es - valljuk be - inkabb az beteg dolog kicsit hha ez igy van, nem az h most nincs igy<br /><br />jo persze konyvekrol, filmekrol, eloadasokrol lehet fogok tovabbra is irni, de valszeg kicsit kevesbe lesz szemelyes ez a dolog. meg foleg rendszertelen<br /><br />azert kosz mindenkinek a commentelest, it was fun :)<br /><br />ps: jah, es aki nagyon ra van kattanva a temara eszreveheti, h a frugalwre blog sem frissul. ez sem veletlen, sokkal tobb ertelme van a <a href="mailto:frugalware-devel@frugalware.org" target="_self">fw-dev</a> listara irogatni blogolas helyett, konnyebb megbeszelni a felvetett kerdeseket, ha nagyon akarja ezt tovabbra is vmi weboldalszeru cuccon figyelni, akkor azt <a href="http://search.gmane.org/?query=&amp;group=gmane.linux.frugalware.devel&amp;author=VMiklos&amp;sort=date" target="_self">itt</a> megteheti. aki meg rss maniac, az valaszthat 4fele rss kozul <a href="http://dir.gmane.org/gmane.linux.frugalware.devel" target="_self">itt</a>
++++
